// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package userproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMessageResponse struct {
	Userid               int32    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessageResponse) Reset()         { *m = UserMessageResponse{} }
func (m *UserMessageResponse) String() string { return proto.CompactTextString(m) }
func (*UserMessageResponse) ProtoMessage()    {}
func (*UserMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *UserMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessageResponse.Unmarshal(m, b)
}
func (m *UserMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessageResponse.Marshal(b, m, deterministic)
}
func (m *UserMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessageResponse.Merge(m, src)
}
func (m *UserMessageResponse) XXX_Size() int {
	return xxx_messageInfo_UserMessageResponse.Size(m)
}
func (m *UserMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessageResponse proto.InternalMessageInfo

func (m *UserMessageResponse) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *UserMessageResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserMessageRequest struct {
	Userid               int32    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessageRequest) Reset()         { *m = UserMessageRequest{} }
func (m *UserMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UserMessageRequest) ProtoMessage()    {}
func (*UserMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *UserMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessageRequest.Unmarshal(m, b)
}
func (m *UserMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessageRequest.Marshal(b, m, deterministic)
}
func (m *UserMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessageRequest.Merge(m, src)
}
func (m *UserMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UserMessageRequest.Size(m)
}
func (m *UserMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessageRequest proto.InternalMessageInfo

func (m *UserMessageRequest) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

//
//UserMessageRequestByName is message to send the users name to the service
type UserMessageRequestByName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessageRequestByName) Reset()         { *m = UserMessageRequestByName{} }
func (m *UserMessageRequestByName) String() string { return proto.CompactTextString(m) }
func (*UserMessageRequestByName) ProtoMessage()    {}
func (*UserMessageRequestByName) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *UserMessageRequestByName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessageRequestByName.Unmarshal(m, b)
}
func (m *UserMessageRequestByName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessageRequestByName.Marshal(b, m, deterministic)
}
func (m *UserMessageRequestByName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessageRequestByName.Merge(m, src)
}
func (m *UserMessageRequestByName) XXX_Size() int {
	return xxx_messageInfo_UserMessageRequestByName.Size(m)
}
func (m *UserMessageRequestByName) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessageRequestByName.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessageRequestByName proto.InternalMessageInfo

func (m *UserMessageRequestByName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//
//Create a user request.
type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//
//Create a user response.
type CreatedUserResponse struct {
	User                 *UserMessageResponse `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatedUserResponse) Reset()         { *m = CreatedUserResponse{} }
func (m *CreatedUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreatedUserResponse) ProtoMessage()    {}
func (*CreatedUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *CreatedUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedUserResponse.Unmarshal(m, b)
}
func (m *CreatedUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedUserResponse.Marshal(b, m, deterministic)
}
func (m *CreatedUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedUserResponse.Merge(m, src)
}
func (m *CreatedUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreatedUserResponse.Size(m)
}
func (m *CreatedUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedUserResponse proto.InternalMessageInfo

func (m *CreatedUserResponse) GetUser() *UserMessageResponse {
	if m != nil {
		return m.User
	}
	return nil
}

//
//Request to delete a user.
type DeleteUserRequest struct {
	User                 *UserMessageRequest `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUser() *UserMessageRequest {
	if m != nil {
		return m.User
	}
	return nil
}

//
//Response on a deleteuser request.
type DeleteUserResponse struct {
	IsDeleted            bool     `protobuf:"varint,1,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

//
//FindUserRequest is the request to find a user by his userid message
type FindUserRequest struct {
	User                 *UserMessageRequest `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FindUserRequest) Reset()         { *m = FindUserRequest{} }
func (m *FindUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserRequest) ProtoMessage()    {}
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{7}
}

func (m *FindUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserRequest.Unmarshal(m, b)
}
func (m *FindUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserRequest.Marshal(b, m, deterministic)
}
func (m *FindUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserRequest.Merge(m, src)
}
func (m *FindUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserRequest.Size(m)
}
func (m *FindUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserRequest proto.InternalMessageInfo

func (m *FindUserRequest) GetUser() *UserMessageRequest {
	if m != nil {
		return m.User
	}
	return nil
}

//
//FindUserByNameRequest is the request to find a user by his username.
type FindUserByNameRequest struct {
	User                 *UserMessageRequestByName `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FindUserByNameRequest) Reset()         { *m = FindUserByNameRequest{} }
func (m *FindUserByNameRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserByNameRequest) ProtoMessage()    {}
func (*FindUserByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{8}
}

func (m *FindUserByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserByNameRequest.Unmarshal(m, b)
}
func (m *FindUserByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserByNameRequest.Marshal(b, m, deterministic)
}
func (m *FindUserByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserByNameRequest.Merge(m, src)
}
func (m *FindUserByNameRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserByNameRequest.Size(m)
}
func (m *FindUserByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserByNameRequest proto.InternalMessageInfo

func (m *FindUserByNameRequest) GetUser() *UserMessageRequestByName {
	if m != nil {
		return m.User
	}
	return nil
}

//
//FindUserResponse is the response on a find user request.
type FindUserResponse struct {
	User                 *UserMessageResponse `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindUserResponse) Reset()         { *m = FindUserResponse{} }
func (m *FindUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserResponse) ProtoMessage()    {}
func (*FindUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{9}
}

func (m *FindUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserResponse.Unmarshal(m, b)
}
func (m *FindUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserResponse.Marshal(b, m, deterministic)
}
func (m *FindUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserResponse.Merge(m, src)
}
func (m *FindUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserResponse.Size(m)
}
func (m *FindUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserResponse proto.InternalMessageInfo

func (m *FindUserResponse) GetUser() *UserMessageResponse {
	if m != nil {
		return m.User
	}
	return nil
}

//
//ChangeUserRequest will be a request to change a user.
type ChangeUserRequest struct {
	Change               *UserMessageResponse `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChangeUserRequest) Reset()         { *m = ChangeUserRequest{} }
func (m *ChangeUserRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeUserRequest) ProtoMessage()    {}
func (*ChangeUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{10}
}

func (m *ChangeUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserRequest.Unmarshal(m, b)
}
func (m *ChangeUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserRequest.Marshal(b, m, deterministic)
}
func (m *ChangeUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserRequest.Merge(m, src)
}
func (m *ChangeUserRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeUserRequest.Size(m)
}
func (m *ChangeUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserRequest proto.InternalMessageInfo

func (m *ChangeUserRequest) GetChange() *UserMessageResponse {
	if m != nil {
		return m.Change
	}
	return nil
}

//
//ChangeUserRequest will be a request to change a user.
type ChangeUserResponse struct {
	Change               bool     `protobuf:"varint,1,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeUserResponse) Reset()         { *m = ChangeUserResponse{} }
func (m *ChangeUserResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeUserResponse) ProtoMessage()    {}
func (*ChangeUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{11}
}

func (m *ChangeUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserResponse.Unmarshal(m, b)
}
func (m *ChangeUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserResponse.Marshal(b, m, deterministic)
}
func (m *ChangeUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserResponse.Merge(m, src)
}
func (m *ChangeUserResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeUserResponse.Size(m)
}
func (m *ChangeUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserResponse proto.InternalMessageInfo

func (m *ChangeUserResponse) GetChange() bool {
	if m != nil {
		return m.Change
	}
	return false
}

//
//AllUsersRequest will be a request for all users.
type AllUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllUsersRequest) Reset()         { *m = AllUsersRequest{} }
func (m *AllUsersRequest) String() string { return proto.CompactTextString(m) }
func (*AllUsersRequest) ProtoMessage()    {}
func (*AllUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{12}
}

func (m *AllUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllUsersRequest.Unmarshal(m, b)
}
func (m *AllUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllUsersRequest.Marshal(b, m, deterministic)
}
func (m *AllUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllUsersRequest.Merge(m, src)
}
func (m *AllUsersRequest) XXX_Size() int {
	return xxx_messageInfo_AllUsersRequest.Size(m)
}
func (m *AllUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllUsersRequest proto.InternalMessageInfo

//
//AllUsersResponse will by a list of all users.
type AllUsersResponse struct {
	Users                []*UserMessageResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AllUsersResponse) Reset()         { *m = AllUsersResponse{} }
func (m *AllUsersResponse) String() string { return proto.CompactTextString(m) }
func (*AllUsersResponse) ProtoMessage()    {}
func (*AllUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{13}
}

func (m *AllUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllUsersResponse.Unmarshal(m, b)
}
func (m *AllUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllUsersResponse.Marshal(b, m, deterministic)
}
func (m *AllUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllUsersResponse.Merge(m, src)
}
func (m *AllUsersResponse) XXX_Size() int {
	return xxx_messageInfo_AllUsersResponse.Size(m)
}
func (m *AllUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllUsersResponse proto.InternalMessageInfo

func (m *AllUsersResponse) GetUsers() []*UserMessageResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserMessageResponse)(nil), "userproto.UserMessageResponse")
	proto.RegisterType((*UserMessageRequest)(nil), "userproto.UserMessageRequest")
	proto.RegisterType((*UserMessageRequestByName)(nil), "userproto.UserMessageRequestByName")
	proto.RegisterType((*CreateUserRequest)(nil), "userproto.CreateUserRequest")
	proto.RegisterType((*CreatedUserResponse)(nil), "userproto.CreatedUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "userproto.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "userproto.DeleteUserResponse")
	proto.RegisterType((*FindUserRequest)(nil), "userproto.FindUserRequest")
	proto.RegisterType((*FindUserByNameRequest)(nil), "userproto.FindUserByNameRequest")
	proto.RegisterType((*FindUserResponse)(nil), "userproto.FindUserResponse")
	proto.RegisterType((*ChangeUserRequest)(nil), "userproto.ChangeUserRequest")
	proto.RegisterType((*ChangeUserResponse)(nil), "userproto.ChangeUserResponse")
	proto.RegisterType((*AllUsersRequest)(nil), "userproto.AllUsersRequest")
	proto.RegisterType((*AllUsersResponse)(nil), "userproto.AllUsersResponse")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdd, 0xae, 0xd2, 0x40,
	0x14, 0x85, 0xa9, 0xfc, 0x04, 0x36, 0x89, 0xd0, 0x21, 0x92, 0xa6, 0x02, 0x69, 0xc6, 0x0b, 0xb9,
	0x30, 0x4d, 0xac, 0x46, 0xaf, 0x11, 0x24, 0x1a, 0xd4, 0x68, 0x89, 0x0f, 0x50, 0xdb, 0x0d, 0x36,
	0x81, 0x82, 0x1d, 0x30, 0x39, 0x2f, 0x7b, 0x9e, 0xe5, 0xa4, 0xd3, 0xe9, 0xcf, 0xb4, 0xe5, 0x1c,
	0x12, 0xee, 0xda, 0x99, 0xb5, 0xbf, 0x3d, 0x7b, 0xcd, 0x1a, 0xe8, 0x9e, 0x19, 0x86, 0xcc, 0x3c,
	0x86, 0x87, 0xd3, 0x81, 0x74, 0xa2, 0x1f, 0xfe, 0x49, 0x67, 0x30, 0xf8, 0xcd, 0x30, 0xfc, 0x8e,
	0x8c, 0x39, 0x5b, 0xb4, 0x91, 0x1d, 0x0f, 0x01, 0x43, 0x32, 0x84, 0x56, 0xa4, 0xf1, 0x3d, 0x4d,
	0x31, 0x94, 0x69, 0xd3, 0x16, 0x7f, 0x84, 0x40, 0x23, 0x70, 0xf6, 0xa8, 0x3d, 0x33, 0x94, 0x69,
	0xc7, 0xe6, 0xdf, 0xf4, 0x0d, 0x10, 0x09, 0xf1, 0xef, 0x8c, 0xec, 0x74, 0x89, 0x40, 0x4d, 0xd0,
	0xca, 0xea, 0x4f, 0x77, 0x3f, 0x9c, 0x3d, 0xa6, 0x74, 0x25, 0x47, 0x7f, 0x0d, 0xea, 0x3c, 0x44,
	0xe7, 0x84, 0x51, 0x55, 0x02, 0xaf, 0x12, 0x7e, 0x85, 0x41, 0x2c, 0xf4, 0x62, 0xa5, 0x98, 0xc4,
	0x82, 0x46, 0xd4, 0x99, 0x4b, 0xbb, 0xd6, 0xc4, 0x4c, 0x47, 0x37, 0x2b, 0xe6, 0xb6, 0xb9, 0x96,
	0x2e, 0x41, 0x5d, 0xe0, 0x0e, 0xe5, 0x9e, 0x6f, 0x25, 0xd0, 0xf8, 0x12, 0x88, 0x8b, 0x05, 0xc7,
	0x02, 0x92, 0xe7, 0x88, 0x13, 0x8d, 0xa0, 0xe3, 0xb3, 0x78, 0x3d, 0x36, 0xa7, 0x6d, 0x67, 0x0b,
	0x74, 0x01, 0xbd, 0xa5, 0x1f, 0x78, 0x37, 0x76, 0xfe, 0x09, 0x2f, 0x12, 0x4a, 0xec, 0x6d, 0xc2,
	0xfa, 0x28, 0xb1, 0x5e, 0x3d, 0xca, 0x12, 0x95, 0x89, 0x27, 0xfd, 0xec, 0x5c, 0x37, 0x78, 0xbb,
	0x02, 0x75, 0xfe, 0xd7, 0x09, 0xb6, 0x92, 0xb7, 0x1f, 0xa0, 0xe5, 0xf2, 0xc5, 0x2b, 0x51, 0x42,
	0x1d, 0x45, 0x2f, 0x0f, 0xcb, 0xc2, 0x9b, 0xa3, 0xb5, 0x53, 0xb5, 0x0a, 0xbd, 0xd9, 0x6e, 0x17,
	0x49, 0x99, 0x68, 0x4c, 0xbf, 0x40, 0x3f, 0x5b, 0x12, 0xe5, 0xef, 0xa1, 0xc9, 0x1f, 0x8b, 0xa6,
	0x18, 0xf5, 0x2b, 0xce, 0x12, 0x8b, 0xad, 0xfb, 0xba, 0x28, 0x23, 0xdf, 0x00, 0xdc, 0x34, 0xb1,
	0x64, 0x94, 0x2b, 0x2f, 0x05, 0x59, 0x9f, 0x94, 0x76, 0x25, 0x87, 0x69, 0x8d, 0x7c, 0x86, 0xf6,
	0x46, 0xf8, 0x4e, 0xf4, 0x9c, 0xba, 0x10, 0x12, 0xfd, 0x65, 0xe5, 0x5e, 0x8a, 0xf9, 0x05, 0xcf,
	0x37, 0x52, 0x20, 0x88, 0x51, 0x51, 0x20, 0x65, 0xe5, 0x29, 0xe4, 0x0a, 0xc0, 0x4b, 0xd3, 0x2d,
	0xcd, 0x59, 0x7a, 0x3c, 0xfa, 0xf8, 0xc2, 0x6e, 0x1e, 0xe6, 0xa6, 0x37, 0x29, 0x9b, 0x56, 0x4c,
	0x8b, 0x04, 0x2b, 0x5f, 0x3f, 0xad, 0x91, 0x35, 0x0c, 0x43, 0x74, 0xd1, 0xff, 0x8f, 0xb3, 0xc0,
	0x5b, 0x63, 0xe0, 0x25, 0x77, 0x2c, 0x39, 0x58, 0xc8, 0x82, 0x34, 0x6e, 0x31, 0x14, 0xb4, 0xf6,
	0xa7, 0xc5, 0x77, 0xde, 0x3d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x50, 0xdf, 0x9a, 0xb6, 0x4a, 0x05,
	0x00, 0x00,
}
