// Code generated by protoc-gen-go. DO NOT EDIT.
// source: show.proto

package showproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShowMessage struct {
	CinemaId             int32    `protobuf:"varint,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	MovieId              int32    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowMessage) Reset()         { *m = ShowMessage{} }
func (m *ShowMessage) String() string { return proto.CompactTextString(m) }
func (*ShowMessage) ProtoMessage()    {}
func (*ShowMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{0}
}
func (m *ShowMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowMessage.Unmarshal(m, b)
}
func (m *ShowMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowMessage.Marshal(b, m, deterministic)
}
func (dst *ShowMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowMessage.Merge(dst, src)
}
func (m *ShowMessage) XXX_Size() int {
	return xxx_messageInfo_ShowMessage.Size(m)
}
func (m *ShowMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ShowMessage proto.InternalMessageInfo

func (m *ShowMessage) GetCinemaId() int32 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

func (m *ShowMessage) GetMovieId() int32 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type CreateShowRequest struct {
	CreateData           *ShowMessage `protobuf:"bytes,1,opt,name=createData,proto3" json:"createData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateShowRequest) Reset()         { *m = CreateShowRequest{} }
func (m *CreateShowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShowRequest) ProtoMessage()    {}
func (*CreateShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{1}
}
func (m *CreateShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowRequest.Unmarshal(m, b)
}
func (m *CreateShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowRequest.Marshal(b, m, deterministic)
}
func (dst *CreateShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowRequest.Merge(dst, src)
}
func (m *CreateShowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShowRequest.Size(m)
}
func (m *CreateShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowRequest proto.InternalMessageInfo

func (m *CreateShowRequest) GetCreateData() *ShowMessage {
	if m != nil {
		return m.CreateData
	}
	return nil
}

type CreateShowResponse struct {
	CreateShowId         int32    `protobuf:"varint,1,opt,name=createShowId,proto3" json:"createShowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowResponse) Reset()         { *m = CreateShowResponse{} }
func (m *CreateShowResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShowResponse) ProtoMessage()    {}
func (*CreateShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{2}
}
func (m *CreateShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowResponse.Unmarshal(m, b)
}
func (m *CreateShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowResponse.Marshal(b, m, deterministic)
}
func (dst *CreateShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowResponse.Merge(dst, src)
}
func (m *CreateShowResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShowResponse.Size(m)
}
func (m *CreateShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowResponse proto.InternalMessageInfo

func (m *CreateShowResponse) GetCreateShowId() int32 {
	if m != nil {
		return m.CreateShowId
	}
	return 0
}

type DeleteShowRequest struct {
	DeleteShowId         int32    `protobuf:"varint,1,opt,name=deleteShowId,proto3" json:"deleteShowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowRequest) Reset()         { *m = DeleteShowRequest{} }
func (m *DeleteShowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowRequest) ProtoMessage()    {}
func (*DeleteShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{3}
}
func (m *DeleteShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowRequest.Unmarshal(m, b)
}
func (m *DeleteShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowRequest.Merge(dst, src)
}
func (m *DeleteShowRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowRequest.Size(m)
}
func (m *DeleteShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowRequest proto.InternalMessageInfo

func (m *DeleteShowRequest) GetDeleteShowId() int32 {
	if m != nil {
		return m.DeleteShowId
	}
	return 0
}

type DeleteShowResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowResponse) Reset()         { *m = DeleteShowResponse{} }
func (m *DeleteShowResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShowResponse) ProtoMessage()    {}
func (*DeleteShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{4}
}
func (m *DeleteShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowResponse.Unmarshal(m, b)
}
func (m *DeleteShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowResponse.Merge(dst, src)
}
func (m *DeleteShowResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShowResponse.Size(m)
}
func (m *DeleteShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowResponse proto.InternalMessageInfo

func (m *DeleteShowResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type DeleteShowConnectedCinemaRequest struct {
	CinemaId             int32    `protobuf:"varint,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowConnectedCinemaRequest) Reset()         { *m = DeleteShowConnectedCinemaRequest{} }
func (m *DeleteShowConnectedCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowConnectedCinemaRequest) ProtoMessage()    {}
func (*DeleteShowConnectedCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{5}
}
func (m *DeleteShowConnectedCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowConnectedCinemaRequest.Unmarshal(m, b)
}
func (m *DeleteShowConnectedCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowConnectedCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteShowConnectedCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowConnectedCinemaRequest.Merge(dst, src)
}
func (m *DeleteShowConnectedCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowConnectedCinemaRequest.Size(m)
}
func (m *DeleteShowConnectedCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowConnectedCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowConnectedCinemaRequest proto.InternalMessageInfo

func (m *DeleteShowConnectedCinemaRequest) GetCinemaId() int32 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

type DeleteShowConnectedCinemaResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowConnectedCinemaResponse) Reset()         { *m = DeleteShowConnectedCinemaResponse{} }
func (m *DeleteShowConnectedCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShowConnectedCinemaResponse) ProtoMessage()    {}
func (*DeleteShowConnectedCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{6}
}
func (m *DeleteShowConnectedCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowConnectedCinemaResponse.Unmarshal(m, b)
}
func (m *DeleteShowConnectedCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowConnectedCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteShowConnectedCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowConnectedCinemaResponse.Merge(dst, src)
}
func (m *DeleteShowConnectedCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShowConnectedCinemaResponse.Size(m)
}
func (m *DeleteShowConnectedCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowConnectedCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowConnectedCinemaResponse proto.InternalMessageInfo

func (m *DeleteShowConnectedCinemaResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type DeleteShowConnectedMovieRequest struct {
	MovieId              int32    `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowConnectedMovieRequest) Reset()         { *m = DeleteShowConnectedMovieRequest{} }
func (m *DeleteShowConnectedMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowConnectedMovieRequest) ProtoMessage()    {}
func (*DeleteShowConnectedMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{7}
}
func (m *DeleteShowConnectedMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowConnectedMovieRequest.Unmarshal(m, b)
}
func (m *DeleteShowConnectedMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowConnectedMovieRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteShowConnectedMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowConnectedMovieRequest.Merge(dst, src)
}
func (m *DeleteShowConnectedMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowConnectedMovieRequest.Size(m)
}
func (m *DeleteShowConnectedMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowConnectedMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowConnectedMovieRequest proto.InternalMessageInfo

func (m *DeleteShowConnectedMovieRequest) GetMovieId() int32 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type DeleteShowConnectedMovieResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowConnectedMovieResponse) Reset()         { *m = DeleteShowConnectedMovieResponse{} }
func (m *DeleteShowConnectedMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShowConnectedMovieResponse) ProtoMessage()    {}
func (*DeleteShowConnectedMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{8}
}
func (m *DeleteShowConnectedMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowConnectedMovieResponse.Unmarshal(m, b)
}
func (m *DeleteShowConnectedMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowConnectedMovieResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteShowConnectedMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowConnectedMovieResponse.Merge(dst, src)
}
func (m *DeleteShowConnectedMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShowConnectedMovieResponse.Size(m)
}
func (m *DeleteShowConnectedMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowConnectedMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowConnectedMovieResponse proto.InternalMessageInfo

func (m *DeleteShowConnectedMovieResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type ListShowRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShowRequest) Reset()         { *m = ListShowRequest{} }
func (m *ListShowRequest) String() string { return proto.CompactTextString(m) }
func (*ListShowRequest) ProtoMessage()    {}
func (*ListShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{9}
}
func (m *ListShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShowRequest.Unmarshal(m, b)
}
func (m *ListShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShowRequest.Marshal(b, m, deterministic)
}
func (dst *ListShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShowRequest.Merge(dst, src)
}
func (m *ListShowRequest) XXX_Size() int {
	return xxx_messageInfo_ListShowRequest.Size(m)
}
func (m *ListShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListShowRequest proto.InternalMessageInfo

type ListShowResponse struct {
	ShowId               []int32        `protobuf:"varint,1,rep,packed,name=showId,proto3" json:"showId,omitempty"`
	AllShowsData         []*ShowMessage `protobuf:"bytes,2,rep,name=allShowsData,proto3" json:"allShowsData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListShowResponse) Reset()         { *m = ListShowResponse{} }
func (m *ListShowResponse) String() string { return proto.CompactTextString(m) }
func (*ListShowResponse) ProtoMessage()    {}
func (*ListShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{10}
}
func (m *ListShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShowResponse.Unmarshal(m, b)
}
func (m *ListShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShowResponse.Marshal(b, m, deterministic)
}
func (dst *ListShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShowResponse.Merge(dst, src)
}
func (m *ListShowResponse) XXX_Size() int {
	return xxx_messageInfo_ListShowResponse.Size(m)
}
func (m *ListShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListShowResponse proto.InternalMessageInfo

func (m *ListShowResponse) GetShowId() []int32 {
	if m != nil {
		return m.ShowId
	}
	return nil
}

func (m *ListShowResponse) GetAllShowsData() []*ShowMessage {
	if m != nil {
		return m.AllShowsData
	}
	return nil
}

type FindShowConnectedMovieRequest struct {
	MovieId              int32    `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindShowConnectedMovieRequest) Reset()         { *m = FindShowConnectedMovieRequest{} }
func (m *FindShowConnectedMovieRequest) String() string { return proto.CompactTextString(m) }
func (*FindShowConnectedMovieRequest) ProtoMessage()    {}
func (*FindShowConnectedMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{11}
}
func (m *FindShowConnectedMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindShowConnectedMovieRequest.Unmarshal(m, b)
}
func (m *FindShowConnectedMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindShowConnectedMovieRequest.Marshal(b, m, deterministic)
}
func (dst *FindShowConnectedMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindShowConnectedMovieRequest.Merge(dst, src)
}
func (m *FindShowConnectedMovieRequest) XXX_Size() int {
	return xxx_messageInfo_FindShowConnectedMovieRequest.Size(m)
}
func (m *FindShowConnectedMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindShowConnectedMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindShowConnectedMovieRequest proto.InternalMessageInfo

func (m *FindShowConnectedMovieRequest) GetMovieId() int32 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type FindShowConnectedMovieResponse struct {
	MovieData            []*ShowMessage `protobuf:"bytes,1,rep,name=movieData,proto3" json:"movieData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindShowConnectedMovieResponse) Reset()         { *m = FindShowConnectedMovieResponse{} }
func (m *FindShowConnectedMovieResponse) String() string { return proto.CompactTextString(m) }
func (*FindShowConnectedMovieResponse) ProtoMessage()    {}
func (*FindShowConnectedMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{12}
}
func (m *FindShowConnectedMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindShowConnectedMovieResponse.Unmarshal(m, b)
}
func (m *FindShowConnectedMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindShowConnectedMovieResponse.Marshal(b, m, deterministic)
}
func (dst *FindShowConnectedMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindShowConnectedMovieResponse.Merge(dst, src)
}
func (m *FindShowConnectedMovieResponse) XXX_Size() int {
	return xxx_messageInfo_FindShowConnectedMovieResponse.Size(m)
}
func (m *FindShowConnectedMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindShowConnectedMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindShowConnectedMovieResponse proto.InternalMessageInfo

func (m *FindShowConnectedMovieResponse) GetMovieData() []*ShowMessage {
	if m != nil {
		return m.MovieData
	}
	return nil
}

type FindShowConnectedCinemaRequest struct {
	CinemaId             int32    `protobuf:"varint,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindShowConnectedCinemaRequest) Reset()         { *m = FindShowConnectedCinemaRequest{} }
func (m *FindShowConnectedCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*FindShowConnectedCinemaRequest) ProtoMessage()    {}
func (*FindShowConnectedCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{13}
}
func (m *FindShowConnectedCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindShowConnectedCinemaRequest.Unmarshal(m, b)
}
func (m *FindShowConnectedCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindShowConnectedCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *FindShowConnectedCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindShowConnectedCinemaRequest.Merge(dst, src)
}
func (m *FindShowConnectedCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_FindShowConnectedCinemaRequest.Size(m)
}
func (m *FindShowConnectedCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindShowConnectedCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindShowConnectedCinemaRequest proto.InternalMessageInfo

func (m *FindShowConnectedCinemaRequest) GetCinemaId() int32 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

type FindShowConnectedCinemaResponse struct {
	CinemaData           []*ShowMessage `protobuf:"bytes,1,rep,name=cinemaData,proto3" json:"cinemaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindShowConnectedCinemaResponse) Reset()         { *m = FindShowConnectedCinemaResponse{} }
func (m *FindShowConnectedCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*FindShowConnectedCinemaResponse) ProtoMessage()    {}
func (*FindShowConnectedCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_show_d28da28913b33079, []int{14}
}
func (m *FindShowConnectedCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindShowConnectedCinemaResponse.Unmarshal(m, b)
}
func (m *FindShowConnectedCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindShowConnectedCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *FindShowConnectedCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindShowConnectedCinemaResponse.Merge(dst, src)
}
func (m *FindShowConnectedCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_FindShowConnectedCinemaResponse.Size(m)
}
func (m *FindShowConnectedCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindShowConnectedCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindShowConnectedCinemaResponse proto.InternalMessageInfo

func (m *FindShowConnectedCinemaResponse) GetCinemaData() []*ShowMessage {
	if m != nil {
		return m.CinemaData
	}
	return nil
}

func init() {
	proto.RegisterType((*ShowMessage)(nil), "showproto.ShowMessage")
	proto.RegisterType((*CreateShowRequest)(nil), "showproto.CreateShowRequest")
	proto.RegisterType((*CreateShowResponse)(nil), "showproto.CreateShowResponse")
	proto.RegisterType((*DeleteShowRequest)(nil), "showproto.DeleteShowRequest")
	proto.RegisterType((*DeleteShowResponse)(nil), "showproto.DeleteShowResponse")
	proto.RegisterType((*DeleteShowConnectedCinemaRequest)(nil), "showproto.DeleteShowConnectedCinemaRequest")
	proto.RegisterType((*DeleteShowConnectedCinemaResponse)(nil), "showproto.DeleteShowConnectedCinemaResponse")
	proto.RegisterType((*DeleteShowConnectedMovieRequest)(nil), "showproto.DeleteShowConnectedMovieRequest")
	proto.RegisterType((*DeleteShowConnectedMovieResponse)(nil), "showproto.DeleteShowConnectedMovieResponse")
	proto.RegisterType((*ListShowRequest)(nil), "showproto.ListShowRequest")
	proto.RegisterType((*ListShowResponse)(nil), "showproto.ListShowResponse")
	proto.RegisterType((*FindShowConnectedMovieRequest)(nil), "showproto.FindShowConnectedMovieRequest")
	proto.RegisterType((*FindShowConnectedMovieResponse)(nil), "showproto.FindShowConnectedMovieResponse")
	proto.RegisterType((*FindShowConnectedCinemaRequest)(nil), "showproto.FindShowConnectedCinemaRequest")
	proto.RegisterType((*FindShowConnectedCinemaResponse)(nil), "showproto.FindShowConnectedCinemaResponse")
}

func init() { proto.RegisterFile("show.proto", fileDescriptor_show_d28da28913b33079) }

var fileDescriptor_show_d28da28913b33079 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x6e, 0x5a, 0x52, 0xd2, 0xaf, 0x91, 0x20, 0x73, 0x08, 0xc6, 0x50, 0x1a, 0xf6, 0x94, 0x3e,
	0x94, 0x43, 0x41, 0x3c, 0x5a, 0xc4, 0xc5, 0x05, 0xa9, 0x2a, 0xb9, 0x18, 0x09, 0x89, 0xa3, 0xb1,
	0x17, 0x62, 0x29, 0xf1, 0x06, 0xaf, 0x43, 0xf8, 0x73, 0xfc, 0x37, 0xe4, 0xc5, 0x5e, 0xaf, 0x89,
	0xed, 0x58, 0xbd, 0x79, 0x67, 0xbf, 0xc7, 0x78, 0xf6, 0x1b, 0x40, 0xce, 0xc4, 0x7a, 0xb2, 0x8c,
	0x45, 0x22, 0xe8, 0x20, 0xfd, 0x56, 0x9f, 0xcc, 0xc1, 0xe1, 0xe7, 0x99, 0x58, 0x4f, 0xb9, 0x94,
	0xde, 0x0f, 0x4e, 0x36, 0x7a, 0x7e, 0x18, 0xf1, 0x85, 0x77, 0x13, 0x58, 0x9d, 0x51, 0x67, 0xdc,
	0x75, 0xf5, 0x99, 0x2c, 0xdc, 0x5f, 0x88, 0x5f, 0x21, 0xbf, 0x09, 0xac, 0x5d, 0x75, 0x95, 0x1f,
	0xd9, 0x2d, 0x06, 0x4e, 0xcc, 0xbd, 0x84, 0xa7, 0x52, 0x2e, 0xff, 0xb9, 0xe2, 0x32, 0xa1, 0x57,
	0x80, 0xaf, 0x8a, 0xd7, 0x5e, 0xe2, 0x29, 0xb1, 0xc3, 0x8b, 0xe1, 0x44, 0x3b, 0x4f, 0x0c, 0x5b,
	0xd7, 0x40, 0xb2, 0x37, 0x20, 0x53, 0x4c, 0x2e, 0x45, 0x24, 0x39, 0x31, 0xf4, 0x7d, 0x5d, 0xd5,
	0xcd, 0x95, 0x6a, 0xec, 0x35, 0x06, 0xd7, 0x7c, 0xce, 0xcb, 0x6d, 0x30, 0xf4, 0x03, 0x5d, 0x2c,
	0x88, 0x66, 0x8d, 0x9d, 0x83, 0x4c, 0x62, 0x66, 0x39, 0xc4, 0xbe, 0x17, 0xc9, 0x35, 0x8f, 0x15,
	0xa7, 0xe7, 0x66, 0x27, 0xf6, 0x1e, 0xa3, 0x02, 0xed, 0x88, 0x28, 0xe2, 0x7e, 0xc2, 0x03, 0x47,
	0x8d, 0x29, 0x77, 0x6d, 0x98, 0x23, 0xbb, 0xc2, 0xf3, 0x06, 0xfe, 0x16, 0xf3, 0x2b, 0x1c, 0x57,
	0x90, 0xa7, 0xe9, 0x43, 0xe4, 0xde, 0xc6, 0x3b, 0x75, 0xca, 0xef, 0x74, 0x59, 0xd9, 0x79, 0x46,
	0xde, 0x62, 0x3c, 0xc0, 0x83, 0x4f, 0xa1, 0x4c, 0x8c, 0xd1, 0xb2, 0xef, 0x78, 0x58, 0x94, 0x0a,
	0xba, 0xcc, 0x07, 0xbd, 0x37, 0xee, 0xba, 0xd9, 0x89, 0x2e, 0xd1, 0xf7, 0xe6, 0xf3, 0x14, 0x2a,
	0x55, 0x1e, 0x76, 0x47, 0x7b, 0x0d, 0x79, 0x28, 0x61, 0xd9, 0x5b, 0x1c, 0x7d, 0x0c, 0xa3, 0xe0,
	0x2e, 0x7f, 0xfc, 0x05, 0xcf, 0xea, 0xa8, 0x59, 0xc3, 0x2f, 0x71, 0xa0, 0xc0, 0x59, 0x4a, 0x9b,
	0xba, 0x2a, 0x80, 0xec, 0x5d, 0x85, 0x6e, 0xfb, 0x04, 0x7c, 0xc5, 0x71, 0x2d, 0x3b, 0x6b, 0x2b,
	0xdd, 0x1e, 0x55, 0x69, 0xd1, 0x97, 0x81, 0xbc, 0xf8, 0xd3, 0xc5, 0xbd, 0xf4, 0x8e, 0x6e, 0x81,
	0x62, 0x8d, 0xe8, 0xa9, 0x41, 0xdd, 0x58, 0x55, 0xfb, 0xa8, 0xe6, 0xf6, 0x5f, 0x2f, 0x6c, 0x27,
	0x15, 0x2b, 0x82, 0x53, 0x12, 0xdb, 0x58, 0xb8, 0x92, 0xd8, 0xe6, 0x56, 0xb1, 0x1d, 0xfa, 0x8d,
	0xc7, 0xb5, 0xf9, 0xa7, 0xb3, 0x4a, 0x76, 0xf5, 0x8c, 0xed, 0xf3, 0x76, 0x60, 0xed, 0xbc, 0x82,
	0x55, 0x97, 0x7f, 0x3a, 0x6d, 0xd6, 0x32, 0xf3, 0x66, 0x9f, 0xb5, 0xc2, 0x6a, 0xdb, 0x0f, 0xe8,
	0xe5, 0x7b, 0x42, 0xb6, 0x41, 0xfd, 0x6f, 0x9f, 0xec, 0x27, 0x95, 0x77, 0x5a, 0x26, 0xc6, 0xa3,
	0x9a, 0xd4, 0xd0, 0x89, 0xc1, 0x6c, 0xce, 0xa5, 0x7d, 0xda, 0x06, 0xaa, 0x3d, 0x05, 0x86, 0xd5,
	0xfb, 0x43, 0xe3, 0x26, 0x9d, 0xd2, 0xb4, 0x4e, 0x5a, 0x20, 0x73, 0xc3, 0x6f, 0xfb, 0x0a, 0xf7,
	0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x8f, 0xe5, 0xa0, 0xaf, 0x06, 0x00, 0x00,
}
