// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema.proto

package cinemahallproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SeatMessage struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column               int32    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatMessage) Reset()         { *m = SeatMessage{} }
func (m *SeatMessage) String() string { return proto.CompactTextString(m) }
func (*SeatMessage) ProtoMessage()    {}
func (*SeatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{0}
}
func (m *SeatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatMessage.Unmarshal(m, b)
}
func (m *SeatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatMessage.Marshal(b, m, deterministic)
}
func (dst *SeatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatMessage.Merge(dst, src)
}
func (m *SeatMessage) XXX_Size() int {
	return xxx_messageInfo_SeatMessage.Size(m)
}
func (m *SeatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SeatMessage proto.InternalMessageInfo

func (m *SeatMessage) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *SeatMessage) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type CreateCinemaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Row                  int32    `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Column               int32    `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaRequest) Reset()         { *m = CreateCinemaRequest{} }
func (m *CreateCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaRequest) ProtoMessage()    {}
func (*CreateCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{1}
}
func (m *CreateCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaRequest.Unmarshal(m, b)
}
func (m *CreateCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaRequest.Merge(dst, src)
}
func (m *CreateCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaRequest.Size(m)
}
func (m *CreateCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaRequest proto.InternalMessageInfo

func (m *CreateCinemaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCinemaRequest) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *CreateCinemaRequest) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type CreateCinemaResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaResponse) Reset()         { *m = CreateCinemaResponse{} }
func (m *CreateCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaResponse) ProtoMessage()    {}
func (*CreateCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{2}
}
func (m *CreateCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaResponse.Unmarshal(m, b)
}
func (m *CreateCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaResponse.Merge(dst, src)
}
func (m *CreateCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaResponse.Size(m)
}
func (m *CreateCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaResponse proto.InternalMessageInfo

func (m *CreateCinemaResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCinemaResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCinemaRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaRequest) Reset()         { *m = DeleteCinemaRequest{} }
func (m *DeleteCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaRequest) ProtoMessage()    {}
func (*DeleteCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{3}
}
func (m *DeleteCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaRequest.Unmarshal(m, b)
}
func (m *DeleteCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaRequest.Merge(dst, src)
}
func (m *DeleteCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaRequest.Size(m)
}
func (m *DeleteCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaRequest proto.InternalMessageInfo

func (m *DeleteCinemaRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCinemaResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaResponse) Reset()         { *m = DeleteCinemaResponse{} }
func (m *DeleteCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaResponse) ProtoMessage()    {}
func (*DeleteCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{4}
}
func (m *DeleteCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaResponse.Unmarshal(m, b)
}
func (m *DeleteCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaResponse.Merge(dst, src)
}
func (m *DeleteCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaResponse.Size(m)
}
func (m *DeleteCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaResponse proto.InternalMessageInfo

func (m *DeleteCinemaResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type ReservationRequest struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seatreservation      []*SeatMessage `protobuf:"bytes,2,rep,name=seatreservation,proto3" json:"seatreservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{5}
}
func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (dst *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(dst, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

func (m *ReservationRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReservationRequest) GetSeatreservation() []*SeatMessage {
	if m != nil {
		return m.Seatreservation
	}
	return nil
}

type ReservationResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationResponse) Reset()         { *m = ReservationResponse{} }
func (m *ReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReservationResponse) ProtoMessage()    {}
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{6}
}
func (m *ReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationResponse.Unmarshal(m, b)
}
func (m *ReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationResponse.Marshal(b, m, deterministic)
}
func (dst *ReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationResponse.Merge(dst, src)
}
func (m *ReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReservationResponse.Size(m)
}
func (m *ReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationResponse proto.InternalMessageInfo

func (m *ReservationResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type StornoRequest struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seatstorno           []*SeatMessage `protobuf:"bytes,2,rep,name=seatstorno,proto3" json:"seatstorno,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StornoRequest) Reset()         { *m = StornoRequest{} }
func (m *StornoRequest) String() string { return proto.CompactTextString(m) }
func (*StornoRequest) ProtoMessage()    {}
func (*StornoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{7}
}
func (m *StornoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StornoRequest.Unmarshal(m, b)
}
func (m *StornoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StornoRequest.Marshal(b, m, deterministic)
}
func (dst *StornoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StornoRequest.Merge(dst, src)
}
func (m *StornoRequest) XXX_Size() int {
	return xxx_messageInfo_StornoRequest.Size(m)
}
func (m *StornoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StornoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StornoRequest proto.InternalMessageInfo

func (m *StornoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StornoRequest) GetSeatstorno() []*SeatMessage {
	if m != nil {
		return m.Seatstorno
	}
	return nil
}

type StornoResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StornoResponse) Reset()         { *m = StornoResponse{} }
func (m *StornoResponse) String() string { return proto.CompactTextString(m) }
func (*StornoResponse) ProtoMessage()    {}
func (*StornoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{8}
}
func (m *StornoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StornoResponse.Unmarshal(m, b)
}
func (m *StornoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StornoResponse.Marshal(b, m, deterministic)
}
func (dst *StornoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StornoResponse.Merge(dst, src)
}
func (m *StornoResponse) XXX_Size() int {
	return xxx_messageInfo_StornoResponse.Size(m)
}
func (m *StornoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StornoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StornoResponse proto.InternalMessageInfo

func (m *StornoResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type CheckSeatsRequest struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seatcheck            []*SeatMessage `protobuf:"bytes,2,rep,name=seatcheck,proto3" json:"seatcheck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CheckSeatsRequest) Reset()         { *m = CheckSeatsRequest{} }
func (m *CheckSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*CheckSeatsRequest) ProtoMessage()    {}
func (*CheckSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{9}
}
func (m *CheckSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSeatsRequest.Unmarshal(m, b)
}
func (m *CheckSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSeatsRequest.Marshal(b, m, deterministic)
}
func (dst *CheckSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSeatsRequest.Merge(dst, src)
}
func (m *CheckSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_CheckSeatsRequest.Size(m)
}
func (m *CheckSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSeatsRequest proto.InternalMessageInfo

func (m *CheckSeatsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckSeatsRequest) GetSeatcheck() []*SeatMessage {
	if m != nil {
		return m.Seatcheck
	}
	return nil
}

type CheckSeatsResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSeatsResponse) Reset()         { *m = CheckSeatsResponse{} }
func (m *CheckSeatsResponse) String() string { return proto.CompactTextString(m) }
func (*CheckSeatsResponse) ProtoMessage()    {}
func (*CheckSeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{10}
}
func (m *CheckSeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSeatsResponse.Unmarshal(m, b)
}
func (m *CheckSeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSeatsResponse.Marshal(b, m, deterministic)
}
func (dst *CheckSeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSeatsResponse.Merge(dst, src)
}
func (m *CheckSeatsResponse) XXX_Size() int {
	return xxx_messageInfo_CheckSeatsResponse.Size(m)
}
func (m *CheckSeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSeatsResponse proto.InternalMessageInfo

func (m *CheckSeatsResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type FreeSeatsRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreeSeatsRequest) Reset()         { *m = FreeSeatsRequest{} }
func (m *FreeSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*FreeSeatsRequest) ProtoMessage()    {}
func (*FreeSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{11}
}
func (m *FreeSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreeSeatsRequest.Unmarshal(m, b)
}
func (m *FreeSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreeSeatsRequest.Marshal(b, m, deterministic)
}
func (dst *FreeSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreeSeatsRequest.Merge(dst, src)
}
func (m *FreeSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_FreeSeatsRequest.Size(m)
}
func (m *FreeSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FreeSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FreeSeatsRequest proto.InternalMessageInfo

func (m *FreeSeatsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FreeSeatsResponse struct {
	Freeseats            []*SeatMessage `protobuf:"bytes,1,rep,name=freeseats,proto3" json:"freeseats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FreeSeatsResponse) Reset()         { *m = FreeSeatsResponse{} }
func (m *FreeSeatsResponse) String() string { return proto.CompactTextString(m) }
func (*FreeSeatsResponse) ProtoMessage()    {}
func (*FreeSeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_548a63850a330f10, []int{12}
}
func (m *FreeSeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreeSeatsResponse.Unmarshal(m, b)
}
func (m *FreeSeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreeSeatsResponse.Marshal(b, m, deterministic)
}
func (dst *FreeSeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreeSeatsResponse.Merge(dst, src)
}
func (m *FreeSeatsResponse) XXX_Size() int {
	return xxx_messageInfo_FreeSeatsResponse.Size(m)
}
func (m *FreeSeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FreeSeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FreeSeatsResponse proto.InternalMessageInfo

func (m *FreeSeatsResponse) GetFreeseats() []*SeatMessage {
	if m != nil {
		return m.Freeseats
	}
	return nil
}

func init() {
	proto.RegisterType((*SeatMessage)(nil), "cinemahallproto.SeatMessage")
	proto.RegisterType((*CreateCinemaRequest)(nil), "cinemahallproto.CreateCinemaRequest")
	proto.RegisterType((*CreateCinemaResponse)(nil), "cinemahallproto.CreateCinemaResponse")
	proto.RegisterType((*DeleteCinemaRequest)(nil), "cinemahallproto.DeleteCinemaRequest")
	proto.RegisterType((*DeleteCinemaResponse)(nil), "cinemahallproto.DeleteCinemaResponse")
	proto.RegisterType((*ReservationRequest)(nil), "cinemahallproto.ReservationRequest")
	proto.RegisterType((*ReservationResponse)(nil), "cinemahallproto.ReservationResponse")
	proto.RegisterType((*StornoRequest)(nil), "cinemahallproto.StornoRequest")
	proto.RegisterType((*StornoResponse)(nil), "cinemahallproto.StornoResponse")
	proto.RegisterType((*CheckSeatsRequest)(nil), "cinemahallproto.CheckSeatsRequest")
	proto.RegisterType((*CheckSeatsResponse)(nil), "cinemahallproto.CheckSeatsResponse")
	proto.RegisterType((*FreeSeatsRequest)(nil), "cinemahallproto.FreeSeatsRequest")
	proto.RegisterType((*FreeSeatsResponse)(nil), "cinemahallproto.FreeSeatsResponse")
}

func init() { proto.RegisterFile("cinema.proto", fileDescriptor_cinema_548a63850a330f10) }

var fileDescriptor_cinema_548a63850a330f10 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x86, 0x6f, 0xd2, 0x6b, 0x30, 0xa7, 0x7a, 0x3f, 0xa6, 0x97, 0x12, 0x82, 0x68, 0x9d, 0xb6,
	0xd0, 0x85, 0x66, 0x51, 0x17, 0x42, 0x71, 0x57, 0xe9, 0x46, 0x44, 0x48, 0x05, 0x41, 0x10, 0x19,
	0xd3, 0xa3, 0x0d, 0xa6, 0x99, 0x3a, 0x93, 0xda, 0xff, 0xe1, 0x2f, 0x96, 0x4c, 0xd2, 0x34, 0xdf,
	0xe9, 0x2e, 0x93, 0x3c, 0xf3, 0x9c, 0x97, 0xc3, 0x1b, 0x78, 0xe2, 0xf9, 0x21, 0xee, 0x98, 0xb3,
	0x17, 0x3c, 0xe2, 0xe4, 0x36, 0x39, 0x6d, 0x59, 0x10, 0xa8, 0x17, 0xf4, 0x2d, 0xf4, 0xd7, 0xc8,
	0xa2, 0x8f, 0x28, 0x25, 0xfb, 0x85, 0xe4, 0x0e, 0x7a, 0x82, 0x1f, 0x2d, 0x6d, 0xa4, 0xcd, 0x1e,
	0xb9, 0xf1, 0x23, 0x19, 0x82, 0xe1, 0xf1, 0xe0, 0xb0, 0x0b, 0x2d, 0x5d, 0xbd, 0x4c, 0x4f, 0x74,
	0x0d, 0x83, 0xa5, 0x40, 0x16, 0xe1, 0x52, 0x19, 0x5d, 0xfc, 0x73, 0x40, 0x19, 0x11, 0x02, 0xd7,
	0x21, 0xdb, 0xa1, 0x32, 0x98, 0xae, 0x7a, 0x3e, 0x49, 0xf5, 0x3a, 0x69, 0xaf, 0x20, 0x5d, 0xc0,
	0x43, 0x51, 0x2a, 0xf7, 0x3c, 0x94, 0x58, 0x6b, 0xbd, 0x01, 0xdd, 0xdf, 0xa4, 0x52, 0xdd, 0xdf,
	0xd0, 0x29, 0x0c, 0xde, 0x63, 0x80, 0xe5, 0x40, 0x09, 0xa6, 0x65, 0x98, 0x03, 0x0f, 0x45, 0x2c,
	0x1d, 0x31, 0x04, 0x83, 0x85, 0xf2, 0x88, 0x42, 0xb1, 0x8f, 0xdd, 0xf4, 0x44, 0x03, 0x20, 0x2e,
	0x4a, 0x14, 0x7f, 0x59, 0xe4, 0xf3, 0xb0, 0xc1, 0x4a, 0x56, 0x70, 0x2b, 0x91, 0x45, 0xe2, 0x4c,
	0x5a, 0xfa, 0xa8, 0x37, 0xeb, 0xcf, 0x9f, 0x39, 0xa5, 0x8d, 0x3b, 0xb9, 0x75, 0xbb, 0xe5, 0x4b,
	0xf4, 0x35, 0x0c, 0x0a, 0xd3, 0x3a, 0xc2, 0x7d, 0x83, 0xa7, 0xeb, 0x88, 0x8b, 0x90, 0x37, 0xe5,
	0x7a, 0x07, 0x10, 0x8f, 0x90, 0x0a, 0xba, 0x28, 0x52, 0x8e, 0xa7, 0x33, 0xb8, 0x39, 0xe9, 0x3b,
	0x82, 0x7c, 0x87, 0xfb, 0xe5, 0x16, 0xbd, 0xdf, 0xb1, 0x49, 0x36, 0x85, 0x59, 0x80, 0x19, 0xcb,
	0xbd, 0x18, 0xbc, 0x28, 0xcb, 0x19, 0xa7, 0xaf, 0x80, 0xe4, 0x07, 0x74, 0xc4, 0xa1, 0x70, 0xb7,
	0x12, 0x88, 0x6d, 0x69, 0xe8, 0x27, 0xb8, 0xcf, 0x31, 0xa9, 0x70, 0x01, 0xe6, 0x4f, 0x81, 0xa8,
	0x76, 0x60, 0x69, 0x97, 0x44, 0xcc, 0xf0, 0xf9, 0xbf, 0x6b, 0x30, 0x92, 0x52, 0x91, 0x2f, 0x60,
	0x24, 0x3d, 0x26, 0x93, 0xca, 0xed, 0x9a, 0xbf, 0xc6, 0x9e, 0x76, 0x50, 0x49, 0x3a, 0x7a, 0x15,
	0x8b, 0x93, 0xf6, 0xd6, 0x88, 0x6b, 0xda, 0x5f, 0x23, 0xae, 0x2b, 0x3f, 0xbd, 0x22, 0x5f, 0xa1,
	0x9f, 0x2b, 0x1e, 0x19, 0x57, 0xee, 0x55, 0x7f, 0x02, 0x7b, 0xd2, 0x0e, 0x65, 0xee, 0x0f, 0x60,
	0x24, 0x35, 0x22, 0xcf, 0xab, 0xbb, 0xcc, 0xd7, 0xd7, 0x7e, 0xd1, 0xf8, 0x3d, 0xb7, 0x01, 0x38,
	0x17, 0x81, 0xd0, 0xea, 0xe2, 0xca, 0x35, 0xb4, 0xc7, 0xad, 0x4c, 0x26, 0xfe, 0x0c, 0x66, 0xd6,
	0x07, 0xf2, 0xb2, 0x72, 0xa7, 0xdc, 0x27, 0x9b, 0xb6, 0x21, 0x27, 0xeb, 0x0f, 0x43, 0x7d, 0x7a,
	0xf3, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x14, 0xa4, 0x3f, 0xde, 0x87, 0x05, 0x00, 0x00,
}
