// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema.proto

package cinemahallproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCinemaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Row                  int64    `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Column               int64    `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaRequest) Reset()         { *m = CreateCinemaRequest{} }
func (m *CreateCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaRequest) ProtoMessage()    {}
func (*CreateCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{0}
}
func (m *CreateCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaRequest.Unmarshal(m, b)
}
func (m *CreateCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaRequest.Merge(dst, src)
}
func (m *CreateCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaRequest.Size(m)
}
func (m *CreateCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaRequest proto.InternalMessageInfo

func (m *CreateCinemaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCinemaRequest) GetRow() int64 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *CreateCinemaRequest) GetColumn() int64 {
	if m != nil {
		return m.Column
	}
	return 0
}

type CreateCinemaResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaResponse) Reset()         { *m = CreateCinemaResponse{} }
func (m *CreateCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaResponse) ProtoMessage()    {}
func (*CreateCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{1}
}
func (m *CreateCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaResponse.Unmarshal(m, b)
}
func (m *CreateCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaResponse.Merge(dst, src)
}
func (m *CreateCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaResponse.Size(m)
}
func (m *CreateCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaResponse proto.InternalMessageInfo

func (m *CreateCinemaResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCinemaResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCinemaRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaRequest) Reset()         { *m = DeleteCinemaRequest{} }
func (m *DeleteCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaRequest) ProtoMessage()    {}
func (*DeleteCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{2}
}
func (m *DeleteCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaRequest.Unmarshal(m, b)
}
func (m *DeleteCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaRequest.Merge(dst, src)
}
func (m *DeleteCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaRequest.Size(m)
}
func (m *DeleteCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaRequest proto.InternalMessageInfo

func (m *DeleteCinemaRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCinemaResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaResponse) Reset()         { *m = DeleteCinemaResponse{} }
func (m *DeleteCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaResponse) ProtoMessage()    {}
func (*DeleteCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{3}
}
func (m *DeleteCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaResponse.Unmarshal(m, b)
}
func (m *DeleteCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaResponse.Merge(dst, src)
}
func (m *DeleteCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaResponse.Size(m)
}
func (m *DeleteCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaResponse proto.InternalMessageInfo

func (m *DeleteCinemaResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type SeatMessage struct {
	Row                  int64    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column               int64    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatMessage) Reset()         { *m = SeatMessage{} }
func (m *SeatMessage) String() string { return proto.CompactTextString(m) }
func (*SeatMessage) ProtoMessage()    {}
func (*SeatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{4}
}
func (m *SeatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatMessage.Unmarshal(m, b)
}
func (m *SeatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatMessage.Marshal(b, m, deterministic)
}
func (dst *SeatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatMessage.Merge(dst, src)
}
func (m *SeatMessage) XXX_Size() int {
	return xxx_messageInfo_SeatMessage.Size(m)
}
func (m *SeatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SeatMessage proto.InternalMessageInfo

func (m *SeatMessage) GetRow() int64 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *SeatMessage) GetColumn() int64 {
	if m != nil {
		return m.Column
	}
	return 0
}

type ReservationRequest struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seatreservation      []*SeatMessage `protobuf:"bytes,2,rep,name=seatreservation,proto3" json:"seatreservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{5}
}
func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (dst *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(dst, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

func (m *ReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReservationRequest) GetSeatreservation() []*SeatMessage {
	if m != nil {
		return m.Seatreservation
	}
	return nil
}

type ReservationResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationResponse) Reset()         { *m = ReservationResponse{} }
func (m *ReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReservationResponse) ProtoMessage()    {}
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{6}
}
func (m *ReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationResponse.Unmarshal(m, b)
}
func (m *ReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationResponse.Marshal(b, m, deterministic)
}
func (dst *ReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationResponse.Merge(dst, src)
}
func (m *ReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReservationResponse.Size(m)
}
func (m *ReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationResponse proto.InternalMessageInfo

func (m *ReservationResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type StornoRequest struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seatstorno           []*SeatMessage `protobuf:"bytes,2,rep,name=seatstorno,proto3" json:"seatstorno,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StornoRequest) Reset()         { *m = StornoRequest{} }
func (m *StornoRequest) String() string { return proto.CompactTextString(m) }
func (*StornoRequest) ProtoMessage()    {}
func (*StornoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{7}
}
func (m *StornoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StornoRequest.Unmarshal(m, b)
}
func (m *StornoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StornoRequest.Marshal(b, m, deterministic)
}
func (dst *StornoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StornoRequest.Merge(dst, src)
}
func (m *StornoRequest) XXX_Size() int {
	return xxx_messageInfo_StornoRequest.Size(m)
}
func (m *StornoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StornoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StornoRequest proto.InternalMessageInfo

func (m *StornoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StornoRequest) GetSeatstorno() []*SeatMessage {
	if m != nil {
		return m.Seatstorno
	}
	return nil
}

type StornoResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StornoResponse) Reset()         { *m = StornoResponse{} }
func (m *StornoResponse) String() string { return proto.CompactTextString(m) }
func (*StornoResponse) ProtoMessage()    {}
func (*StornoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{8}
}
func (m *StornoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StornoResponse.Unmarshal(m, b)
}
func (m *StornoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StornoResponse.Marshal(b, m, deterministic)
}
func (dst *StornoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StornoResponse.Merge(dst, src)
}
func (m *StornoResponse) XXX_Size() int {
	return xxx_messageInfo_StornoResponse.Size(m)
}
func (m *StornoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StornoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StornoResponse proto.InternalMessageInfo

func (m *StornoResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type AvailableSeatsRequest struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seats                []*SeatMessage `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AvailableSeatsRequest) Reset()         { *m = AvailableSeatsRequest{} }
func (m *AvailableSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*AvailableSeatsRequest) ProtoMessage()    {}
func (*AvailableSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{9}
}
func (m *AvailableSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableSeatsRequest.Unmarshal(m, b)
}
func (m *AvailableSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableSeatsRequest.Marshal(b, m, deterministic)
}
func (dst *AvailableSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableSeatsRequest.Merge(dst, src)
}
func (m *AvailableSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_AvailableSeatsRequest.Size(m)
}
func (m *AvailableSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableSeatsRequest proto.InternalMessageInfo

func (m *AvailableSeatsRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AvailableSeatsRequest) GetSeats() []*SeatMessage {
	if m != nil {
		return m.Seats
	}
	return nil
}

type AvailableSeatsResponse struct {
	Available            bool     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableSeatsResponse) Reset()         { *m = AvailableSeatsResponse{} }
func (m *AvailableSeatsResponse) String() string { return proto.CompactTextString(m) }
func (*AvailableSeatsResponse) ProtoMessage()    {}
func (*AvailableSeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_250a50cb4ac2bbe2, []int{10}
}
func (m *AvailableSeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableSeatsResponse.Unmarshal(m, b)
}
func (m *AvailableSeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableSeatsResponse.Marshal(b, m, deterministic)
}
func (dst *AvailableSeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableSeatsResponse.Merge(dst, src)
}
func (m *AvailableSeatsResponse) XXX_Size() int {
	return xxx_messageInfo_AvailableSeatsResponse.Size(m)
}
func (m *AvailableSeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableSeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableSeatsResponse proto.InternalMessageInfo

func (m *AvailableSeatsResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func init() {
	proto.RegisterType((*CreateCinemaRequest)(nil), "cinemahallproto.CreateCinemaRequest")
	proto.RegisterType((*CreateCinemaResponse)(nil), "cinemahallproto.CreateCinemaResponse")
	proto.RegisterType((*DeleteCinemaRequest)(nil), "cinemahallproto.DeleteCinemaRequest")
	proto.RegisterType((*DeleteCinemaResponse)(nil), "cinemahallproto.DeleteCinemaResponse")
	proto.RegisterType((*SeatMessage)(nil), "cinemahallproto.SeatMessage")
	proto.RegisterType((*ReservationRequest)(nil), "cinemahallproto.ReservationRequest")
	proto.RegisterType((*ReservationResponse)(nil), "cinemahallproto.ReservationResponse")
	proto.RegisterType((*StornoRequest)(nil), "cinemahallproto.StornoRequest")
	proto.RegisterType((*StornoResponse)(nil), "cinemahallproto.StornoResponse")
	proto.RegisterType((*AvailableSeatsRequest)(nil), "cinemahallproto.AvailableSeatsRequest")
	proto.RegisterType((*AvailableSeatsResponse)(nil), "cinemahallproto.AvailableSeatsResponse")
}

func init() { proto.RegisterFile("cinema.proto", fileDescriptor_cinema_250a50cb4ac2bbe2) }

var fileDescriptor_cinema_250a50cb4ac2bbe2 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0xef, 0xd2, 0x40,
	0x10, 0xfd, 0xb5, 0xd5, 0x46, 0x06, 0x05, 0xb3, 0x20, 0x69, 0x1a, 0xa2, 0x64, 0x05, 0xed, 0xc5,
	0x1e, 0x30, 0xd1, 0xc4, 0x78, 0x31, 0x18, 0x2f, 0xc6, 0x4b, 0x39, 0x98, 0x68, 0x3c, 0x2c, 0x30,
	0xd1, 0x26, 0xa5, 0x8b, 0xdd, 0x02, 0x5f, 0xd1, 0x8f, 0x65, 0xba, 0x5b, 0x4a, 0xff, 0x6c, 0x7f,
	0xe5, 0xb6, 0x3b, 0xf3, 0xe6, 0xbd, 0x37, 0xbb, 0x0f, 0x1e, 0x6f, 0xc3, 0x18, 0xf7, 0xcc, 0x3f,
	0x24, 0x3c, 0xe5, 0x64, 0xa8, 0x6e, 0x7f, 0x58, 0x14, 0xc9, 0x02, 0x5d, 0xc3, 0x68, 0x95, 0x20,
	0x4b, 0x71, 0x25, 0x1b, 0x01, 0xfe, 0x3d, 0xa2, 0x48, 0x09, 0x81, 0x07, 0x31, 0xdb, 0xa3, 0x63,
	0xcc, 0x0c, 0xaf, 0x17, 0xc8, 0x33, 0x79, 0x0a, 0x56, 0xc2, 0xcf, 0x8e, 0x39, 0x33, 0x3c, 0x2b,
	0xc8, 0x8e, 0x64, 0x02, 0xf6, 0x96, 0x47, 0xc7, 0x7d, 0xec, 0x58, 0xb2, 0x98, 0xdf, 0xe8, 0x07,
	0x18, 0x57, 0x49, 0xc5, 0x81, 0xc7, 0x02, 0xb5, 0xac, 0x03, 0x30, 0xc3, 0x5d, 0x4e, 0x6a, 0x86,
	0x3b, 0xba, 0x80, 0xd1, 0x67, 0x8c, 0xb0, 0x6e, 0x48, 0xc1, 0x8c, 0x02, 0xe6, 0xc3, 0xb8, 0x0a,
	0xcb, 0x25, 0x26, 0x60, 0xb3, 0x58, 0x9c, 0x31, 0x91, 0xd8, 0x47, 0x41, 0x7e, 0xa3, 0xef, 0xa1,
	0xbf, 0x46, 0x96, 0x7e, 0x43, 0x21, 0xd8, 0xef, 0x62, 0x17, 0x43, 0xb7, 0x8b, 0x59, 0xd9, 0x25,
	0x02, 0x12, 0xa0, 0xc0, 0xe4, 0xc4, 0xd2, 0x90, 0xc7, 0x2d, 0x76, 0xc8, 0x17, 0x18, 0x0a, 0x64,
	0x69, 0x72, 0x45, 0x3a, 0xe6, 0xcc, 0xf2, 0xfa, 0xcb, 0xa9, 0x5f, 0x7b, 0x71, 0xbf, 0x64, 0x23,
	0xa8, 0x0f, 0xd1, 0x37, 0x30, 0xaa, 0xa8, 0x75, 0x6c, 0xf5, 0x0b, 0x9e, 0xac, 0x53, 0x9e, 0xc4,
	0xbc, 0xcd, 0xd7, 0x47, 0x80, 0x4c, 0x42, 0x48, 0xd0, 0x4d, 0x96, 0x4a, 0x78, 0xea, 0xc1, 0xe0,
	0x42, 0xdf, 0x61, 0xe4, 0x27, 0x3c, 0xfb, 0x74, 0x62, 0x61, 0xc4, 0x36, 0x11, 0x66, 0x6c, 0xa2,
	0xcd, 0xd0, 0x12, 0x1e, 0x4a, 0x81, 0x9b, 0xbc, 0x28, 0x28, 0x7d, 0x07, 0x93, 0x3a, 0x79, 0x6e,
	0x67, 0x0a, 0x3d, 0x76, 0xe9, 0xe4, 0x8e, 0xae, 0x85, 0xe5, 0x3f, 0x0b, 0x6c, 0x15, 0x0f, 0xf2,
	0x1d, 0x6c, 0x95, 0x48, 0x32, 0x6f, 0x28, 0x6a, 0xf2, 0xef, 0x2e, 0x3a, 0x50, 0x4a, 0x9f, 0xde,
	0x65, 0xc4, 0x2a, 0x87, 0x1a, 0x62, 0x4d, 0x8e, 0x35, 0xc4, 0xba, 0x18, 0xd3, 0x3b, 0xf2, 0x03,
	0xfa, 0xa5, 0x24, 0x90, 0x97, 0x8d, 0xb9, 0x66, 0x2a, 0xdd, 0xf9, 0xfd, 0xa0, 0x82, 0xfb, 0x2b,
	0xd8, 0xea, 0x5f, 0xc9, 0xf3, 0xe6, 0xfb, 0x97, 0xf3, 0xe4, 0xbe, 0x68, 0xed, 0x17, 0x64, 0x5b,
	0x18, 0x54, 0x7f, 0x87, 0xbc, 0x6a, 0x0c, 0x69, 0xb3, 0xe1, 0xbe, 0xee, 0xc4, 0x5d, 0x44, 0x36,
	0xb6, 0xec, 0xbf, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x48, 0xd4, 0x12, 0xce, 0x04, 0x00,
	0x00,
}
