// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CinemaMessage struct {
	// Name of the cinema.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Cinema Id
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Data for occupation of seats
	Seats                []*SeatMessage `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	Rownumber            int64          `protobuf:"varint,4,opt,name=rownumber,proto3" json:"rownumber,omitempty"`
	Columnnumber         int64          `protobuf:"varint,5,opt,name=columnnumber,proto3" json:"columnnumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CinemaMessage) Reset()         { *m = CinemaMessage{} }
func (m *CinemaMessage) String() string { return proto.CompactTextString(m) }
func (*CinemaMessage) ProtoMessage()    {}
func (*CinemaMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{0}
}
func (m *CinemaMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaMessage.Unmarshal(m, b)
}
func (m *CinemaMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaMessage.Marshal(b, m, deterministic)
}
func (dst *CinemaMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaMessage.Merge(dst, src)
}
func (m *CinemaMessage) XXX_Size() int {
	return xxx_messageInfo_CinemaMessage.Size(m)
}
func (m *CinemaMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaMessage proto.InternalMessageInfo

func (m *CinemaMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemaMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CinemaMessage) GetSeats() []*SeatMessage {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *CinemaMessage) GetRownumber() int64 {
	if m != nil {
		return m.Rownumber
	}
	return 0
}

func (m *CinemaMessage) GetColumnnumber() int64 {
	if m != nil {
		return m.Columnnumber
	}
	return 0
}

type SeatMessage struct {
	Row                  int64    `protobuf:"varint,4,opt,name=row,proto3" json:"row,omitempty"`
	Column               int64    `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	Occupied             bool     `protobuf:"varint,6,opt,name=occupied,proto3" json:"occupied,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatMessage) Reset()         { *m = SeatMessage{} }
func (m *SeatMessage) String() string { return proto.CompactTextString(m) }
func (*SeatMessage) ProtoMessage()    {}
func (*SeatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{1}
}
func (m *SeatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatMessage.Unmarshal(m, b)
}
func (m *SeatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatMessage.Marshal(b, m, deterministic)
}
func (dst *SeatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatMessage.Merge(dst, src)
}
func (m *SeatMessage) XXX_Size() int {
	return xxx_messageInfo_SeatMessage.Size(m)
}
func (m *SeatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SeatMessage proto.InternalMessageInfo

func (m *SeatMessage) GetRow() int64 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *SeatMessage) GetColumn() int64 {
	if m != nil {
		return m.Column
	}
	return 0
}

func (m *SeatMessage) GetOccupied() bool {
	if m != nil {
		return m.Occupied
	}
	return false
}

type CreateCinemaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Row                  int64    `protobuf:"varint,4,opt,name=row,proto3" json:"row,omitempty"`
	Column               int64    `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaRequest) Reset()         { *m = CreateCinemaRequest{} }
func (m *CreateCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaRequest) ProtoMessage()    {}
func (*CreateCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{2}
}
func (m *CreateCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaRequest.Unmarshal(m, b)
}
func (m *CreateCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaRequest.Merge(dst, src)
}
func (m *CreateCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaRequest.Size(m)
}
func (m *CreateCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaRequest proto.InternalMessageInfo

func (m *CreateCinemaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCinemaRequest) GetRow() int64 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *CreateCinemaRequest) GetColumn() int64 {
	if m != nil {
		return m.Column
	}
	return 0
}

type CreateCinemaResponse struct {
	Data                 *CinemaMessage `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateCinemaResponse) Reset()         { *m = CreateCinemaResponse{} }
func (m *CreateCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaResponse) ProtoMessage()    {}
func (*CreateCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{3}
}
func (m *CreateCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaResponse.Unmarshal(m, b)
}
func (m *CreateCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaResponse.Merge(dst, src)
}
func (m *CreateCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaResponse.Size(m)
}
func (m *CreateCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaResponse proto.InternalMessageInfo

func (m *CreateCinemaResponse) GetData() *CinemaMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteCinemaRequest struct {
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaRequest) Reset()         { *m = DeleteCinemaRequest{} }
func (m *DeleteCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaRequest) ProtoMessage()    {}
func (*DeleteCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{4}
}
func (m *DeleteCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaRequest.Unmarshal(m, b)
}
func (m *DeleteCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaRequest.Merge(dst, src)
}
func (m *DeleteCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaRequest.Size(m)
}
func (m *DeleteCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaRequest proto.InternalMessageInfo

func (m *DeleteCinemaRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCinemaResponse struct {
	Success              bool     `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaResponse) Reset()         { *m = DeleteCinemaResponse{} }
func (m *DeleteCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaResponse) ProtoMessage()    {}
func (*DeleteCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{5}
}
func (m *DeleteCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaResponse.Unmarshal(m, b)
}
func (m *DeleteCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaResponse.Merge(dst, src)
}
func (m *DeleteCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaResponse.Size(m)
}
func (m *DeleteCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaResponse proto.InternalMessageInfo

func (m *DeleteCinemaResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReservationRequest struct {
	Id                   int64          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Seats                []*SeatMessage `protobuf:"bytes,9,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{6}
}
func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (dst *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(dst, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

func (m *ReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReservationRequest) GetSeats() []*SeatMessage {
	if m != nil {
		return m.Seats
	}
	return nil
}

type ReservationResponse struct {
	Seats                []*SeatMessage `protobuf:"bytes,9,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReservationResponse) Reset()         { *m = ReservationResponse{} }
func (m *ReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReservationResponse) ProtoMessage()    {}
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{7}
}
func (m *ReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationResponse.Unmarshal(m, b)
}
func (m *ReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationResponse.Marshal(b, m, deterministic)
}
func (dst *ReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationResponse.Merge(dst, src)
}
func (m *ReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReservationResponse.Size(m)
}
func (m *ReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationResponse proto.InternalMessageInfo

func (m *ReservationResponse) GetSeats() []*SeatMessage {
	if m != nil {
		return m.Seats
	}
	return nil
}

type StornoRequest struct {
	Id                   int64          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Seats                []*SeatMessage `protobuf:"bytes,9,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StornoRequest) Reset()         { *m = StornoRequest{} }
func (m *StornoRequest) String() string { return proto.CompactTextString(m) }
func (*StornoRequest) ProtoMessage()    {}
func (*StornoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{8}
}
func (m *StornoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StornoRequest.Unmarshal(m, b)
}
func (m *StornoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StornoRequest.Marshal(b, m, deterministic)
}
func (dst *StornoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StornoRequest.Merge(dst, src)
}
func (m *StornoRequest) XXX_Size() int {
	return xxx_messageInfo_StornoRequest.Size(m)
}
func (m *StornoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StornoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StornoRequest proto.InternalMessageInfo

func (m *StornoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StornoRequest) GetSeats() []*SeatMessage {
	if m != nil {
		return m.Seats
	}
	return nil
}

type StornoResponse struct {
	Seats                []*SeatMessage `protobuf:"bytes,9,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StornoResponse) Reset()         { *m = StornoResponse{} }
func (m *StornoResponse) String() string { return proto.CompactTextString(m) }
func (*StornoResponse) ProtoMessage()    {}
func (*StornoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{9}
}
func (m *StornoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StornoResponse.Unmarshal(m, b)
}
func (m *StornoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StornoResponse.Marshal(b, m, deterministic)
}
func (dst *StornoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StornoResponse.Merge(dst, src)
}
func (m *StornoResponse) XXX_Size() int {
	return xxx_messageInfo_StornoResponse.Size(m)
}
func (m *StornoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StornoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StornoResponse proto.InternalMessageInfo

func (m *StornoResponse) GetSeats() []*SeatMessage {
	if m != nil {
		return m.Seats
	}
	return nil
}

type AvailableSeatsRequest struct {
	Id                   int64          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Seats                []*SeatMessage `protobuf:"bytes,9,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AvailableSeatsRequest) Reset()         { *m = AvailableSeatsRequest{} }
func (m *AvailableSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*AvailableSeatsRequest) ProtoMessage()    {}
func (*AvailableSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{10}
}
func (m *AvailableSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableSeatsRequest.Unmarshal(m, b)
}
func (m *AvailableSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableSeatsRequest.Marshal(b, m, deterministic)
}
func (dst *AvailableSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableSeatsRequest.Merge(dst, src)
}
func (m *AvailableSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_AvailableSeatsRequest.Size(m)
}
func (m *AvailableSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableSeatsRequest proto.InternalMessageInfo

func (m *AvailableSeatsRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AvailableSeatsRequest) GetSeats() []*SeatMessage {
	if m != nil {
		return m.Seats
	}
	return nil
}

type AvailableSeatsResponse struct {
	Available            bool     `protobuf:"varint,10,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableSeatsResponse) Reset()         { *m = AvailableSeatsResponse{} }
func (m *AvailableSeatsResponse) String() string { return proto.CompactTextString(m) }
func (*AvailableSeatsResponse) ProtoMessage()    {}
func (*AvailableSeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cinema_1316b97a4ea45f23, []int{11}
}
func (m *AvailableSeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableSeatsResponse.Unmarshal(m, b)
}
func (m *AvailableSeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableSeatsResponse.Marshal(b, m, deterministic)
}
func (dst *AvailableSeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableSeatsResponse.Merge(dst, src)
}
func (m *AvailableSeatsResponse) XXX_Size() int {
	return xxx_messageInfo_AvailableSeatsResponse.Size(m)
}
func (m *AvailableSeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableSeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableSeatsResponse proto.InternalMessageInfo

func (m *AvailableSeatsResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func init() {
	proto.RegisterType((*CinemaMessage)(nil), "proto.CinemaMessage")
	proto.RegisterType((*SeatMessage)(nil), "proto.SeatMessage")
	proto.RegisterType((*CreateCinemaRequest)(nil), "proto.CreateCinemaRequest")
	proto.RegisterType((*CreateCinemaResponse)(nil), "proto.CreateCinemaResponse")
	proto.RegisterType((*DeleteCinemaRequest)(nil), "proto.DeleteCinemaRequest")
	proto.RegisterType((*DeleteCinemaResponse)(nil), "proto.DeleteCinemaResponse")
	proto.RegisterType((*ReservationRequest)(nil), "proto.ReservationRequest")
	proto.RegisterType((*ReservationResponse)(nil), "proto.ReservationResponse")
	proto.RegisterType((*StornoRequest)(nil), "proto.StornoRequest")
	proto.RegisterType((*StornoResponse)(nil), "proto.StornoResponse")
	proto.RegisterType((*AvailableSeatsRequest)(nil), "proto.AvailableSeatsRequest")
	proto.RegisterType((*AvailableSeatsResponse)(nil), "proto.AvailableSeatsResponse")
}

func init() { proto.RegisterFile("cinema.proto", fileDescriptor_cinema_1316b97a4ea45f23) }

var fileDescriptor_cinema_1316b97a4ea45f23 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x6f, 0x6b, 0xdb, 0x30,
	0x10, 0xc6, 0xeb, 0xfc, 0x71, 0x93, 0x4b, 0x1b, 0xc6, 0x25, 0x2d, 0x9a, 0x97, 0x81, 0x11, 0x0c,
	0xfc, 0xaa, 0x8c, 0x0c, 0x36, 0xd8, 0x9b, 0x6d, 0x64, 0x0c, 0xf6, 0x62, 0x1b, 0x73, 0x3e, 0x81,
	0xe2, 0x1c, 0xc3, 0x10, 0x5b, 0x99, 0x25, 0xb7, 0x1f, 0x67, 0x5f, 0x6e, 0x1f, 0x64, 0x44, 0x92,
	0x9d, 0xda, 0x75, 0x59, 0x4b, 0x5f, 0xd9, 0xba, 0x3b, 0xfd, 0x74, 0x77, 0xcf, 0x03, 0x67, 0x49,
	0x9a, 0x53, 0x26, 0xae, 0xf6, 0x85, 0xd4, 0x12, 0x87, 0xe6, 0xc3, 0xff, 0x78, 0x70, 0xbe, 0x32,
	0xf1, 0x6f, 0xa4, 0x94, 0xf8, 0x45, 0x88, 0x30, 0xc8, 0x45, 0x46, 0xcc, 0x0b, 0xbd, 0x68, 0x1c,
	0x9b, 0x7f, 0x9c, 0x42, 0x2f, 0xdd, 0xb2, 0x5e, 0xe8, 0x45, 0xfd, 0xb8, 0x97, 0x6e, 0x31, 0x82,
	0xa1, 0x22, 0xa1, 0x15, 0xeb, 0x87, 0xfd, 0x68, 0xb2, 0x44, 0xcb, 0xbc, 0x5a, 0x93, 0xd0, 0x0e,
	0x13, 0xdb, 0x02, 0x5c, 0xc0, 0xb8, 0x90, 0x37, 0x79, 0x99, 0x6d, 0xa8, 0x60, 0x03, 0x03, 0x38,
	0x06, 0x90, 0xc3, 0x59, 0x22, 0x77, 0x65, 0x96, 0xbb, 0x82, 0xa1, 0x29, 0x68, 0xc4, 0xf8, 0x1a,
	0x26, 0xb7, 0xb8, 0xf8, 0x0c, 0xfa, 0x85, 0xbc, 0x71, 0xa8, 0xc3, 0x2f, 0x5e, 0x82, 0x6f, 0x2f,
	0xb8, 0xeb, 0xee, 0x84, 0x01, 0x8c, 0x64, 0x92, 0x94, 0xfb, 0x94, 0xb6, 0xcc, 0x0f, 0xbd, 0x68,
	0x14, 0xd7, 0x67, 0xbe, 0x86, 0xd9, 0xaa, 0x20, 0xa1, 0xc9, 0xce, 0x1e, 0xd3, 0xef, 0x92, 0x94,
	0xee, 0x9c, 0xfd, 0xc1, 0x0f, 0xf2, 0x8f, 0x30, 0x6f, 0x42, 0xd5, 0x5e, 0xe6, 0x8a, 0x30, 0x82,
	0xc1, 0x56, 0x68, 0xc1, 0x4e, 0x43, 0x2f, 0x9a, 0x2c, 0xe7, 0x6e, 0x59, 0x8d, 0xad, 0xc7, 0xa6,
	0x82, 0xbf, 0x82, 0xd9, 0x67, 0xda, 0x51, 0xbb, 0xad, 0xd6, 0xfa, 0xf9, 0x6b, 0x98, 0x37, 0xcb,
	0xdc, 0x43, 0x0c, 0x4e, 0x55, 0x99, 0x24, 0xa4, 0x14, 0x1b, 0x99, 0x81, 0xab, 0x23, 0xff, 0x0e,
	0x18, 0x93, 0xa2, 0xe2, 0x5a, 0xe8, 0x54, 0xe6, 0xf7, 0x70, 0x8f, 0xb2, 0x8e, 0xff, 0x23, 0x2b,
	0xff, 0x00, 0xb3, 0x06, 0xaf, 0x9e, 0xf4, 0xa1, 0x80, 0xaf, 0x70, 0xbe, 0xd6, 0xb2, 0xc8, 0xe5,
	0xd3, 0x7b, 0x79, 0x0f, 0xd3, 0x0a, 0xf5, 0xe8, 0x36, 0x7e, 0xc2, 0xc5, 0xa7, 0x6b, 0x91, 0xee,
	0xc4, 0x66, 0x47, 0x87, 0xb4, 0x7a, 0x7a, 0x3b, 0x6f, 0xe1, 0xb2, 0x8d, 0x74, 0x6d, 0x2d, 0x60,
	0x2c, 0xaa, 0x0c, 0x03, 0x23, 0xd0, 0x31, 0xb0, 0xfc, 0xdb, 0x03, 0xdf, 0xea, 0x89, 0x2b, 0xf0,
	0xad, 0x91, 0x30, 0xa8, 0xcc, 0x72, 0xd7, 0xac, 0xc1, 0x8b, 0xce, 0x9c, 0x7d, 0x8b, 0x9f, 0x1c,
	0x20, 0xd6, 0x24, 0x35, 0xa4, 0xc3, 0x5a, 0x35, 0xa4, 0xcb, 0x4f, 0xfc, 0x04, 0xbf, 0xc0, 0xe4,
	0x96, 0xce, 0xf8, 0xdc, 0x55, 0xdf, 0xf5, 0x52, 0x10, 0x74, 0xa5, 0x6a, 0xce, 0x3b, 0xf0, 0xad,
	0x46, 0x58, 0xd9, 0xbf, 0xa1, 0x7e, 0x70, 0xd1, 0x8a, 0xd6, 0x17, 0x7f, 0xc0, 0xb4, 0xb9, 0x4d,
	0x5c, 0xb8, 0xd2, 0x4e, 0xdd, 0x82, 0x97, 0xf7, 0x64, 0x2b, 0xe0, 0xc6, 0x37, 0xf9, 0x37, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x16, 0x24, 0xe2, 0x10, 0x0e, 0x05, 0x00, 0x00,
}
