# Dockerfile for the movies-services

FROM obraun/vss-protoactor-jenkins as builder
#RUN mkdir -p /app 
COPY . /app
WORKDIR /app/users
 
RUN go build -o users /users/main.go
RUN pwd && ls

FROM iron/go
#COPY --from=builder /app/users/main /app
EXPOSE 8200
ENTRYPOINT ["/app/users"]