// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reservation.proto

package reservationproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message representing a Reservation.
type Reservation struct {
	ResId                int32    `protobuf:"varint,1,opt,name=ResId,proto3" json:"ResId,omitempty"`
	Show                 int32    `protobuf:"varint,2,opt,name=Show,proto3" json:"Show,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reservation) Reset()         { *m = Reservation{} }
func (m *Reservation) String() string { return proto.CompactTextString(m) }
func (*Reservation) ProtoMessage()    {}
func (*Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{0}
}

func (m *Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reservation.Unmarshal(m, b)
}
func (m *Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reservation.Marshal(b, m, deterministic)
}
func (m *Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reservation.Merge(m, src)
}
func (m *Reservation) XXX_Size() int {
	return xxx_messageInfo_Reservation.Size(m)
}
func (m *Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_Reservation proto.InternalMessageInfo

func (m *Reservation) GetResId() int32 {
	if m != nil {
		return m.ResId
	}
	return 0
}

func (m *Reservation) GetShow() int32 {
	if m != nil {
		return m.Show
	}
	return 0
}

// Request for HasReservations
type HasReservationsRequest struct {
	Res                  *Reservation `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HasReservationsRequest) Reset()         { *m = HasReservationsRequest{} }
func (m *HasReservationsRequest) String() string { return proto.CompactTextString(m) }
func (*HasReservationsRequest) ProtoMessage()    {}
func (*HasReservationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{1}
}

func (m *HasReservationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasReservationsRequest.Unmarshal(m, b)
}
func (m *HasReservationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasReservationsRequest.Marshal(b, m, deterministic)
}
func (m *HasReservationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasReservationsRequest.Merge(m, src)
}
func (m *HasReservationsRequest) XXX_Size() int {
	return xxx_messageInfo_HasReservationsRequest.Size(m)
}
func (m *HasReservationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasReservationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasReservationsRequest proto.InternalMessageInfo

func (m *HasReservationsRequest) GetRes() *Reservation {
	if m != nil {
		return m.Res
	}
	return nil
}

// Response for hasReservations
type HasReservationsResponse struct {
	Has                  bool     `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasReservationsResponse) Reset()         { *m = HasReservationsResponse{} }
func (m *HasReservationsResponse) String() string { return proto.CompactTextString(m) }
func (*HasReservationsResponse) ProtoMessage()    {}
func (*HasReservationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{2}
}

func (m *HasReservationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasReservationsResponse.Unmarshal(m, b)
}
func (m *HasReservationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasReservationsResponse.Marshal(b, m, deterministic)
}
func (m *HasReservationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasReservationsResponse.Merge(m, src)
}
func (m *HasReservationsResponse) XXX_Size() int {
	return xxx_messageInfo_HasReservationsResponse.Size(m)
}
func (m *HasReservationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasReservationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasReservationsResponse proto.InternalMessageInfo

func (m *HasReservationsResponse) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

// StreamUsersReservations request.
type StreamUsersReservationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamUsersReservationsRequest) Reset()         { *m = StreamUsersReservationsRequest{} }
func (m *StreamUsersReservationsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamUsersReservationsRequest) ProtoMessage()    {}
func (*StreamUsersReservationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{3}
}

func (m *StreamUsersReservationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamUsersReservationsRequest.Unmarshal(m, b)
}
func (m *StreamUsersReservationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamUsersReservationsRequest.Marshal(b, m, deterministic)
}
func (m *StreamUsersReservationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamUsersReservationsRequest.Merge(m, src)
}
func (m *StreamUsersReservationsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamUsersReservationsRequest.Size(m)
}
func (m *StreamUsersReservationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamUsersReservationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamUsersReservationsRequest proto.InternalMessageInfo

// StreamUsersReservations response.
type StreamUsersReservationsResponse struct {
	Reservations         []*Reservation `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StreamUsersReservationsResponse) Reset()         { *m = StreamUsersReservationsResponse{} }
func (m *StreamUsersReservationsResponse) String() string { return proto.CompactTextString(m) }
func (*StreamUsersReservationsResponse) ProtoMessage()    {}
func (*StreamUsersReservationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{4}
}

func (m *StreamUsersReservationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamUsersReservationsResponse.Unmarshal(m, b)
}
func (m *StreamUsersReservationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamUsersReservationsResponse.Marshal(b, m, deterministic)
}
func (m *StreamUsersReservationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamUsersReservationsResponse.Merge(m, src)
}
func (m *StreamUsersReservationsResponse) XXX_Size() int {
	return xxx_messageInfo_StreamUsersReservationsResponse.Size(m)
}
func (m *StreamUsersReservationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamUsersReservationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamUsersReservationsResponse proto.InternalMessageInfo

func (m *StreamUsersReservationsResponse) GetReservations() []*Reservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

// ShowReservations request.
type ShowReservationsRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 int32    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowReservationsRequest) Reset()         { *m = ShowReservationsRequest{} }
func (m *ShowReservationsRequest) String() string { return proto.CompactTextString(m) }
func (*ShowReservationsRequest) ProtoMessage()    {}
func (*ShowReservationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{5}
}

func (m *ShowReservationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReservationsRequest.Unmarshal(m, b)
}
func (m *ShowReservationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReservationsRequest.Marshal(b, m, deterministic)
}
func (m *ShowReservationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReservationsRequest.Merge(m, src)
}
func (m *ShowReservationsRequest) XXX_Size() int {
	return xxx_messageInfo_ShowReservationsRequest.Size(m)
}
func (m *ShowReservationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReservationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReservationsRequest proto.InternalMessageInfo

func (m *ShowReservationsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShowReservationsRequest) GetUser() int32 {
	if m != nil {
		return m.User
	}
	return 0
}

// ShowReservations response.
type ShowReservationsResponse struct {
	Res                  *Reservation `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ShowReservationsResponse) Reset()         { *m = ShowReservationsResponse{} }
func (m *ShowReservationsResponse) String() string { return proto.CompactTextString(m) }
func (*ShowReservationsResponse) ProtoMessage()    {}
func (*ShowReservationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{6}
}

func (m *ShowReservationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReservationsResponse.Unmarshal(m, b)
}
func (m *ShowReservationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReservationsResponse.Marshal(b, m, deterministic)
}
func (m *ShowReservationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReservationsResponse.Merge(m, src)
}
func (m *ShowReservationsResponse) XXX_Size() int {
	return xxx_messageInfo_ShowReservationsResponse.Size(m)
}
func (m *ShowReservationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReservationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReservationsResponse proto.InternalMessageInfo

func (m *ShowReservationsResponse) GetRes() *Reservation {
	if m != nil {
		return m.Res
	}
	return nil
}

// ChangeReservation request.
type ChangeReservationRequest struct {
	Res                  *Reservation `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChangeReservationRequest) Reset()         { *m = ChangeReservationRequest{} }
func (m *ChangeReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeReservationRequest) ProtoMessage()    {}
func (*ChangeReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{7}
}

func (m *ChangeReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeReservationRequest.Unmarshal(m, b)
}
func (m *ChangeReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeReservationRequest.Marshal(b, m, deterministic)
}
func (m *ChangeReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeReservationRequest.Merge(m, src)
}
func (m *ChangeReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeReservationRequest.Size(m)
}
func (m *ChangeReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeReservationRequest proto.InternalMessageInfo

func (m *ChangeReservationRequest) GetRes() *Reservation {
	if m != nil {
		return m.Res
	}
	return nil
}

// ChangeReservation response.
type ChangeReservationResponse struct {
	Res                  *Reservation `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Changed              bool         `protobuf:"varint,2,opt,name=Changed,proto3" json:"Changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChangeReservationResponse) Reset()         { *m = ChangeReservationResponse{} }
func (m *ChangeReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeReservationResponse) ProtoMessage()    {}
func (*ChangeReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{8}
}

func (m *ChangeReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeReservationResponse.Unmarshal(m, b)
}
func (m *ChangeReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeReservationResponse.Marshal(b, m, deterministic)
}
func (m *ChangeReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeReservationResponse.Merge(m, src)
}
func (m *ChangeReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeReservationResponse.Size(m)
}
func (m *ChangeReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeReservationResponse proto.InternalMessageInfo

func (m *ChangeReservationResponse) GetRes() *Reservation {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *ChangeReservationResponse) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

// DeleteReservation request.
type DeleteReservationRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationRequest) Reset()         { *m = DeleteReservationRequest{} }
func (m *DeleteReservationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationRequest) ProtoMessage()    {}
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{9}
}

func (m *DeleteReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationRequest.Unmarshal(m, b)
}
func (m *DeleteReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationRequest.Merge(m, src)
}
func (m *DeleteReservationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationRequest.Size(m)
}
func (m *DeleteReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationRequest proto.InternalMessageInfo

func (m *DeleteReservationRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// DeleteReservation response.
type DeleteReservationResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationResponse) Reset()         { *m = DeleteReservationResponse{} }
func (m *DeleteReservationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationResponse) ProtoMessage()    {}
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{10}
}

func (m *DeleteReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationResponse.Unmarshal(m, b)
}
func (m *DeleteReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationResponse.Merge(m, src)
}
func (m *DeleteReservationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationResponse.Size(m)
}
func (m *DeleteReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationResponse proto.InternalMessageInfo

func (m *DeleteReservationResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// AcceptReservation request.
type AcceptReservationRequest struct {
	TmpID                int32    `protobuf:"varint,1,opt,name=tmpID,proto3" json:"tmpID,omitempty"`
	Want                 bool     `protobuf:"varint,2,opt,name=want,proto3" json:"want,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptReservationRequest) Reset()         { *m = AcceptReservationRequest{} }
func (m *AcceptReservationRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptReservationRequest) ProtoMessage()    {}
func (*AcceptReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{11}
}

func (m *AcceptReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptReservationRequest.Unmarshal(m, b)
}
func (m *AcceptReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptReservationRequest.Marshal(b, m, deterministic)
}
func (m *AcceptReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptReservationRequest.Merge(m, src)
}
func (m *AcceptReservationRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptReservationRequest.Size(m)
}
func (m *AcceptReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptReservationRequest proto.InternalMessageInfo

func (m *AcceptReservationRequest) GetTmpID() int32 {
	if m != nil {
		return m.TmpID
	}
	return 0
}

func (m *AcceptReservationRequest) GetWant() bool {
	if m != nil {
		return m.Want
	}
	return false
}

// AcceptReservation response.
type AcceptReservationResponse struct {
	FinalID              int32    `protobuf:"varint,1,opt,name=finalID,proto3" json:"finalID,omitempty"`
	Taken                bool     `protobuf:"varint,2,opt,name=taken,proto3" json:"taken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptReservationResponse) Reset()         { *m = AcceptReservationResponse{} }
func (m *AcceptReservationResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptReservationResponse) ProtoMessage()    {}
func (*AcceptReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{12}
}

func (m *AcceptReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptReservationResponse.Unmarshal(m, b)
}
func (m *AcceptReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptReservationResponse.Marshal(b, m, deterministic)
}
func (m *AcceptReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptReservationResponse.Merge(m, src)
}
func (m *AcceptReservationResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptReservationResponse.Size(m)
}
func (m *AcceptReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptReservationResponse proto.InternalMessageInfo

func (m *AcceptReservationResponse) GetFinalID() int32 {
	if m != nil {
		return m.FinalID
	}
	return 0
}

func (m *AcceptReservationResponse) GetTaken() bool {
	if m != nil {
		return m.Taken
	}
	return false
}

// MakeReservation request.
type MakeReservationRequest struct {
	Res                  *Reservation `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MakeReservationRequest) Reset()         { *m = MakeReservationRequest{} }
func (m *MakeReservationRequest) String() string { return proto.CompactTextString(m) }
func (*MakeReservationRequest) ProtoMessage()    {}
func (*MakeReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{13}
}

func (m *MakeReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeReservationRequest.Unmarshal(m, b)
}
func (m *MakeReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeReservationRequest.Marshal(b, m, deterministic)
}
func (m *MakeReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeReservationRequest.Merge(m, src)
}
func (m *MakeReservationRequest) XXX_Size() int {
	return xxx_messageInfo_MakeReservationRequest.Size(m)
}
func (m *MakeReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeReservationRequest proto.InternalMessageInfo

func (m *MakeReservationRequest) GetRes() *Reservation {
	if m != nil {
		return m.Res
	}
	return nil
}

// MakeReservation response.
type MakeReservationResponse struct {
	TmpID                int32    `protobuf:"varint,1,opt,name=tmpID,proto3" json:"tmpID,omitempty"`
	Work                 bool     `protobuf:"varint,2,opt,name=work,proto3" json:"work,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeReservationResponse) Reset()         { *m = MakeReservationResponse{} }
func (m *MakeReservationResponse) String() string { return proto.CompactTextString(m) }
func (*MakeReservationResponse) ProtoMessage()    {}
func (*MakeReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{14}
}

func (m *MakeReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeReservationResponse.Unmarshal(m, b)
}
func (m *MakeReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeReservationResponse.Marshal(b, m, deterministic)
}
func (m *MakeReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeReservationResponse.Merge(m, src)
}
func (m *MakeReservationResponse) XXX_Size() int {
	return xxx_messageInfo_MakeReservationResponse.Size(m)
}
func (m *MakeReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeReservationResponse proto.InternalMessageInfo

func (m *MakeReservationResponse) GetTmpID() int32 {
	if m != nil {
		return m.TmpID
	}
	return 0
}

func (m *MakeReservationResponse) GetWork() bool {
	if m != nil {
		return m.Work
	}
	return false
}

func init() {
	proto.RegisterType((*Reservation)(nil), "reservationproto.Reservation")
	proto.RegisterType((*HasReservationsRequest)(nil), "reservationproto.HasReservationsRequest")
	proto.RegisterType((*HasReservationsResponse)(nil), "reservationproto.HasReservationsResponse")
	proto.RegisterType((*StreamUsersReservationsRequest)(nil), "reservationproto.StreamUsersReservationsRequest")
	proto.RegisterType((*StreamUsersReservationsResponse)(nil), "reservationproto.StreamUsersReservationsResponse")
	proto.RegisterType((*ShowReservationsRequest)(nil), "reservationproto.ShowReservationsRequest")
	proto.RegisterType((*ShowReservationsResponse)(nil), "reservationproto.ShowReservationsResponse")
	proto.RegisterType((*ChangeReservationRequest)(nil), "reservationproto.ChangeReservationRequest")
	proto.RegisterType((*ChangeReservationResponse)(nil), "reservationproto.ChangeReservationResponse")
	proto.RegisterType((*DeleteReservationRequest)(nil), "reservationproto.DeleteReservationRequest")
	proto.RegisterType((*DeleteReservationResponse)(nil), "reservationproto.DeleteReservationResponse")
	proto.RegisterType((*AcceptReservationRequest)(nil), "reservationproto.AcceptReservationRequest")
	proto.RegisterType((*AcceptReservationResponse)(nil), "reservationproto.AcceptReservationResponse")
	proto.RegisterType((*MakeReservationRequest)(nil), "reservationproto.MakeReservationRequest")
	proto.RegisterType((*MakeReservationResponse)(nil), "reservationproto.MakeReservationResponse")
}

func init() { proto.RegisterFile("reservation.proto", fileDescriptor_c1b272c5347b2042) }

var fileDescriptor_c1b272c5347b2042 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xd6, 0x5a, 0xba, 0x4d, 0x57, 0xc4, 0x5a, 0x6b, 0xa2, 0x6e, 0x24, 0x60, 0xf2, 0xd3, 0xe8,
	0xa4, 0x02, 0x43, 0x88, 0x27, 0x1e, 0xa6, 0xf5, 0x81, 0xaa, 0xe2, 0x25, 0x13, 0x3f, 0xc0, 0x2c,
	0x0e, 0x8d, 0x92, 0x25, 0xc1, 0xf6, 0xd8, 0x1b, 0x3f, 0x82, 0x5f, 0x8c, 0xe2, 0x38, 0x6b, 0x88,
	0xcf, 0xd0, 0x55, 0x7b, 0xf3, 0xd9, 0x77, 0xdf, 0xf7, 0xf9, 0xee, 0x7c, 0x86, 0xb1, 0x14, 0x4a,
	0xc8, 0x9f, 0x5c, 0x27, 0x45, 0x3e, 0x2f, 0x65, 0xa1, 0x0b, 0x32, 0x6a, 0x6d, 0x99, 0x1d, 0xf6,
	0x11, 0x86, 0xe1, 0x66, 0x8f, 0x1c, 0xc3, 0x20, 0x14, 0x6a, 0x19, 0xd1, 0xbd, 0x93, 0xbd, 0xd3,
	0x41, 0x58, 0x1b, 0x84, 0xc0, 0x93, 0xab, 0x75, 0x71, 0x47, 0x7b, 0x66, 0xd3, 0xac, 0xd9, 0x12,
	0x9e, 0x7f, 0xe6, 0xaa, 0x15, 0xab, 0x42, 0xf1, 0xe3, 0x56, 0x28, 0x4d, 0xde, 0x40, 0x5f, 0x0a,
	0x65, 0x10, 0x86, 0xe7, 0x2f, 0xe6, 0x5d, 0xca, 0x79, 0x2b, 0x26, 0xac, 0x3c, 0xd9, 0x19, 0x4c,
	0x1c, 0x28, 0x55, 0x16, 0xb9, 0x12, 0x64, 0x04, 0xfd, 0x35, 0xaf, 0xb1, 0x0e, 0xc3, 0x6a, 0xc9,
	0x4e, 0xe0, 0xe5, 0x95, 0x96, 0x82, 0xdf, 0x7c, 0x55, 0x42, 0x62, 0xfc, 0x2c, 0x82, 0x57, 0x5e,
	0x0f, 0x0b, 0x7b, 0x01, 0x4f, 0x5b, 0xb2, 0x2a, 0xfc, 0xfe, 0xff, 0xb5, 0xfe, 0x15, 0xc2, 0x3e,
	0xc1, 0xa4, 0xca, 0x03, 0x96, 0x80, 0x67, 0xd0, 0x4b, 0x9a, 0x0c, 0xf6, 0x12, 0x93, 0xbe, 0x5b,
	0x25, 0x64, 0x93, 0xbe, 0x6a, 0xcd, 0x56, 0x40, 0xdd, 0x70, 0xab, 0xee, 0xc1, 0x09, 0x5c, 0x01,
	0xbd, 0x5c, 0xf3, 0xfc, 0xbb, 0x68, 0x9f, 0xec, 0x5a, 0x8d, 0x18, 0xa6, 0x08, 0xd8, 0x8e, 0xd2,
	0x08, 0x85, 0x83, 0x1a, 0x2d, 0x32, 0xd7, 0x3f, 0x0c, 0x1b, 0x93, 0xcd, 0x80, 0x2e, 0x44, 0x26,
	0x34, 0x26, 0xba, 0x93, 0x41, 0xf6, 0x01, 0xa6, 0x88, 0xaf, 0xd5, 0x44, 0xe1, 0xa0, 0x3e, 0x8c,
	0x6c, 0x9f, 0x34, 0x26, 0x5b, 0x00, 0xbd, 0xb8, 0xbe, 0x16, 0xa5, 0x46, 0x28, 0x8e, 0x61, 0xa0,
	0x6f, 0xca, 0xe5, 0xa2, 0xe9, 0x74, 0x63, 0x54, 0xa5, 0xba, 0xe3, 0xb9, 0xb6, 0x5a, 0xcd, 0x9a,
	0xad, 0x60, 0x8a, 0xa0, 0x6c, 0xc8, 0xe3, 0x24, 0xe7, 0xd9, 0x3d, 0x50, 0x63, 0x1a, 0x02, 0x9e,
	0x8a, 0xdc, 0x62, 0xd5, 0x46, 0xf5, 0x6c, 0xbe, 0xf0, 0xf4, 0x51, 0x0a, 0x75, 0x09, 0x13, 0x07,
	0xca, 0xaa, 0xf2, 0x5f, 0xae, 0x90, 0xe9, 0xfd, 0xe5, 0x0a, 0x99, 0x9e, 0xff, 0xde, 0x87, 0x61,
	0x8b, 0x8a, 0xc4, 0x70, 0xd4, 0x01, 0x25, 0xa7, 0xae, 0x16, 0xfc, 0x0a, 0xc1, 0xeb, 0x2d, 0x3c,
	0xad, 0xc2, 0x0c, 0xc6, 0x4e, 0x52, 0xc9, 0xcc, 0x8d, 0xf7, 0xd5, 0x2f, 0x38, 0xdb, 0xca, 0x77,
	0xc3, 0xe6, 0xf4, 0x0f, 0xc6, 0xe6, 0x6b, 0x48, 0x8c, 0xcd, 0xdf, 0x90, 0x19, 0x8c, 0x9d, 0x17,
	0x84, 0xb1, 0xf9, 0xde, 0x2c, 0xc6, 0xe6, 0x7f, 0x92, 0x09, 0x8c, 0xba, 0x93, 0x84, 0x20, 0x85,
	0xf0, 0x0c, 0xab, 0x60, 0xb6, 0x8d, 0xab, 0xa5, 0xfa, 0x05, 0x13, 0xcf, 0x64, 0x25, 0x6f, 0x11,
	0x98, 0x7f, 0x8e, 0xe9, 0xe0, 0xdd, 0x03, 0x22, 0x2c, 0x7f, 0x0c, 0x47, 0x9d, 0x8f, 0x02, 0x6b,
	0x4e, 0xfc, 0x5b, 0xc2, 0x9a, 0xd3, 0xf3, 0xeb, 0x7c, 0xdb, 0x37, 0xc7, 0xef, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x25, 0xea, 0x47, 0x42, 0x07, 0x00, 0x00,
}
